### ISSUE TITLE
Message: session not created: Chrome version must be between 71 and 75

### ISSUE THREAD

**Issue by turtle-hunter** [InstaPy/instapy-quickstart#108]
When I execute _mac_start.command_ I get the following error log.

I am using Chrome 78.0.3904.97 and updated chromedriver from https://chromedriver.storage.googleapis.com/index.html?path=79.0.3945.16/
and
https://chromedriver.storage.googleapis.com/index.html?path=78.0.3904.70/
but still doesn't work :/

```
Starting InstaPy with quickstart
====================

 ._.  ._.  ._.  ._.  ._.  ._.  ._. 
Workspace in use: "/Users/turtle-hunter/InstaPy"
No handlers could be found for logger "root"

 ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._. 
INFO [2019-11-13 21:34:38] [turtle-hunter]  Using built in instapy-chromedriver executable (version 2.46)
ERROR [2019-11-13 21:34:40] [turtle-hunter]  Message: session not created: Chrome version must be between 71 and 75
  (Driver info: chromedriver=2.46.628411 (3324f4c8be9ff2f70a05a30ebc72ffb013e1a71e),platform=Mac OS X 10.15.1 x86_64)
Traceback (most recent call last):
  File "/Users/turtle-hunter/Library/Python/2.7/lib/python/site-packages/instapy/browser.py", line 163, in set_selenium_local_session
    chrome_options=chrome_options)
  File "/Users/turtle-hunter/Library/Python/2.7/lib/python/site-packages/selenium/webdriver/chrome/webdriver.py", line 81, in __init__
    desired_capabilities=desired_capabilities)
  File "/Users/turtle-hunter/Library/Python/2.7/lib/python/site-packages/selenium/webdriver/remote/webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "/Users/turtle-hunter/Library/Python/2.7/lib/python/site-packages/selenium/webdriver/remote/webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/Users/turtle-hunter/Library/Python/2.7/lib/python/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/Users/turtle-hunter/Library/Python/2.7/lib/python/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
SessionNotCreatedException: Message: session not created: Chrome version must be between 71 and 75
  (Driver info: chromedriver=2.46.628411 (3324f4c8be9ff2f70a05a30ebc72ffb013e1a71e),platform=Mac OS X 10.15.1 x86_64)

Traceback (most recent call last):
  File "../quickstart.py", line 24, in <module>
    headless_browser=False)
  File "/Users/turtle-hunter/Library/Python/2.7/lib/python/site-packages/instapy/instapy.py", line 312, in __init__
    self.set_selenium_local_session()
  File "/Users/turtle-hunter/Library/Python/2.7/lib/python/site-packages/instapy/instapy.py", line 362, in set_selenium_local_session
    raise InstaPyError(err_msg)
instapy.exceptions.InstaPyError: ensure chromedriver is installed at /Users/turtle-hunter/Library/Python/2.7/lib/python/site-packages/instapy_chromedriver/chromedriver_mac64

[Process completed]

```

**Comment by turtle-hunter** [comment]
i downgrade to chrome 74 and now it works, but i get a "Error establishing a database connection" error message :/ i will open a new ticket for that
