### ISSUE TITLE
Quickstart.py issue

### ISSUE THREAD

**Issue by alexdurdan** [InstaPy/instapy-quickstart#115]
Hello,

I am blocked in one error:

Python 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:59:51) [MSC v.1914 64 bit (AMD64)] on win32
Type "copyright", "credits" or "license()" for more information.
>>> 
 RESTART: C:\Users\alexd\AppData\Local\Programs\Python\Python37\Lib\site-packages\quickstart.py 
InstaPy Version: 0.6.6
 ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._. 
Workspace in use: "C:/Users/alexd/InstaPy"
Traceback (most recent call last):
  File "C:\Users\alexd\AppData\Local\Programs\Python\Python37\Lib\site-packages\quickstart.py", line 30, in <module>
    headless_browser=False)
  File "C:\Users\alexd\AppData\Local\Programs\Python\Python37\Lib\site-packages\instapy\instapy.py", line 319, in __init__
    self.logger,
  File "C:\Users\alexd\AppData\Local\Programs\Python\Python37\Lib\site-packages\instapy\browser.py", line 114, in set_selenium_local_session
    options=firefox_options,
  File "C:\Users\alexd\AppData\Local\Programs\Python\Python37\Lib\site-packages\selenium\webdriver\firefox\webdriver.py", line 174, in __init__
    keep_alive=True)
  File "C:\Users\alexd\AppData\Local\Programs\Python\Python37\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "C:\Users\alexd\AppData\Local\Programs\Python\Python37\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "C:\Users\alexd\AppData\Local\Programs\Python\Python37\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\alexd\AppData\Local\Programs\Python\Python37\Lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: Unable to find a matching set of capabilities

>>> 

Please support :(

**Comment by Badmotheruk** [comment]
I have the same issue as above - please advise - i have latest install for firefox and chrome - geckodrive installed and python 3.8.2
