### ISSUE TITLE
Error, unable to determine correct filename for Nonebit win

### ISSUE THREAD

**Issue by incity** [InstaPy/instapy-quickstart#121]
InstaPy Version: 0.6.7
 ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.
Workspace in use: "C:/Users/yin_c/InstaPy"
Error, unable to determine correct filename for Nonebit win
Traceback (most recent call last):
  File "quickstart.py", line 22, in <module>
    session = InstaPy(username=insta_username,
  File "C:\Users\yin_c\AppData\Local\Programs\Python\Python38\lib\site-packages\instapy\instapy.py", line 309, in __init__
    self.browser, err_msg = set_selenium_local_session(
  File "C:\Users\yin_c\AppData\Local\Programs\Python\Python38\lib\site-packages\instapy\browser.py", line 110, in set_selenium_local_session
    driver_path = geckodriver_path or get_geckodriver()
  File "C:\Users\yin_c\AppData\Local\Programs\Python\Python38\lib\site-packages\instapy\browser.py", line 36, in get_geckodriver
    bin_path, sym_path = gdd.download_and_install()
  File "C:\Users\yin_c\AppData\Local\Programs\Python\Python38\lib\site-packages\webdriverdownloader\webdriverdownloader.py", line 174, in download_and_install
    filename_with_path = self.download(version,
  File "C:\Users\yin_c\AppData\Local\Programs\Python\Python38\lib\site-packages\webdriverdownloader\webdriverdownloader.py", line 129, in download
    download_url = self.get_download_url(version, os_name=os_name, bitness=bitness)
  File "C:\Users\yin_c\AppData\Local\Programs\Python\Python38\lib\site-packages\webdriverdownloader\webdriverdownloader.py", line 324, in get_download_url
    raise RuntimeError(info_message)
RuntimeError: Error, unable to determine correct filename for Nonebit win

**Comment by mariomolla** [comment]
Do you know how to solve this problem?

**Comment by thomasgwatson** [comment]
have the same issue but for linux on a raspberry pi

**Comment by Kungfuontoast** [comment]
Any known fix for this? getting the same
