### ISSUE TITLE
Instapy doesn't start

### ISSUE THREAD

**Issue by M4themagier** [InstaPy/instapy-quickstart#124]
Hello, 
when starting mac_start.command I get this issue:

InstaPy Version: 0.6.8
 ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._. 
Workspace in use: "/Users/bunly/InstaPy"
Traceback (most recent call last):
  File "../quickstart.py", line 24, in <module>
    headless_browser=False)
  File "/Users/bunly/anaconda3/lib/python3.7/site-packages/instapy/instapy.py", line 319, in __init__
    self.logger,
  File "/Users/bunly/anaconda3/lib/python3.7/site-packages/instapy/browser.py", line 114, in set_selenium_local_session
    options=firefox_options,
  File "/Users/bunly/anaconda3/lib/python3.7/site-packages/selenium/webdriver/firefox/webdriver.py", line 174, in __init__
    keep_alive=True)
  File "/Users/bunly/anaconda3/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "/Users/bunly/anaconda3/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/Users/bunly/anaconda3/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/Users/bunly/anaconda3/lib/python3.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: Unable to find a matching set of capabilities

logout
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

Can anyone help me please?

KR

**Comment by Badmotheruk** [comment]
I have the same issue as above - please advise - i have latest install for firefox and chrome - geckodrive installed and python 3.8.2
