### ISSUE TITLE
Chrome version must be between 71 & 75 WHAT IS THE PROBLEM ?

### ISSUE THREAD

**Issue by grittdoof** [InstaPy/instapy-quickstart#125]
Last login: Sat Feb 15 00:54:21 on ttys002
aureliengiorgino@Aureliens-MacBook-Pro ~ % /Users/aureliengiorgino/Downloads/instapy-quickstart-master/run/mac_start.command ; exit;
Starting InstaPy with quickstart
====================

 ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._. 
Workspace in use: "/Users/aureliengiorgino/InstaPy"

 ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._. 
INFO [2020-02-15 00:55:56] [aureliengiorgino2]  Using built in instapy-chromedriver executable (version 2.46)
ERROR [2020-02-15 00:55:58] [aureliengiorgino2]  Message: session not created: Chrome version must be between 71 and 75
  (Driver info: chromedriver=2.46.628411 (3324f4c8be9ff2f70a05a30ebc72ffb013e1a71e),platform=Mac OS X 10.15.3 x86_64)
Traceback (most recent call last):
  File "/Users/aureliengiorgino/Library/Python/2.7/lib/python/site-packages/instapy/browser.py", line 163, in set_selenium_local_session
    chrome_options=chrome_options)
  File "/Users/aureliengiorgino/Library/Python/2.7/lib/python/site-packages/selenium/webdriver/chrome/webdriver.py", line 81, in __init__
    desired_capabilities=desired_capabilities)
  File "/Users/aureliengiorgino/Library/Python/2.7/lib/python/site-packages/selenium/webdriver/remote/webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "/Users/aureliengiorgino/Library/Python/2.7/lib/python/site-packages/selenium/webdriver/remote/webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/Users/aureliengiorgino/Library/Python/2.7/lib/python/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/Users/aureliengiorgino/Library/Python/2.7/lib/python/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
SessionNotCreatedException: Message: session not created: Chrome version must be between 71 and 75
  (Driver info: chromedriver=2.46.628411 (3324f4c8be9ff2f70a05a30ebc72ffb013e1a71e),platform=Mac OS X 10.15.3 x86_64)

Traceback (most recent call last):
  File "../quickstart.py", line 24, in <module>
    headless_browser=False)
  File "/Users/aureliengiorgino/Library/Python/2.7/lib/python/site-packages/instapy/instapy.py", line 312, in __init__
    self.set_selenium_local_session()
  File "/Users/aureliengiorgino/Library/Python/2.7/lib/python/site-packages/instapy/instapy.py", line 362, in set_selenium_local_session
    raise InstaPyError(err_msg)
instapy.exceptions.InstaPyError: ensure chromedriver is installed at /Users/aureliengiorgino/Library/Python/2.7/lib/python/site-packages/instapy_chromedriver/chromedriver_mac64

[Process completed]

**Comment by porcherie** [comment]
MAC FIX

Since Instapy seems to work well, in my experience on my Mac, with chromedriver version 2.36, I will downgrade my Google Chrome. I do not use Google Chrome, so this isn't an issue.

Uninstall Google Chrome I used an app called App Cleaner to remove Chrome. After you install App Cleaner, simply drag Google Chrome, from the Applications folder to App Cleaner and Remove All

Download Chrome 65 (Read this step completely before proceeding)

Find and install Chrome 65 from sllimjet.com

After you have installed Chrome 65, open and click the Apple Security Ok button that alerts you to the fact this was downloaded from the internet.

THEN, immediately close Google Chrome completely by holding CMD+Q. This is extremely important! Google Chrome will being its auto-update function. So it must be completely closed, not just the window. We need Chrome to run first and put all its files where it needs them.

Prevent Google Chrome from updating

Open Terminal and type sudo chmod -R 000 ~/Library/Google

You will be asked for your computer password, enter it.

Next run the command sudo rm -rf /Library/Google/

Google Chrome should not be able to auto-update now.

If for some reason Chrome is still updating, or you're unable to run the command in step 3, you can edit your /etc/hosts file to include the following line: 0.0.0.0 tools.google.com

**Comment by MyTimeBox** [comment]
run with python3
