### ISSUE TITLE
error while running quickstart

### ISSUE THREAD

**Issue by ajith468** [InstaPy/instapy-quickstart#142]
Workspace in use: "C:/SPB_Data/InstaPy"
Traceback (most recent call last):
  File "../quickstart.py", line 24, in <module>
    headless_browser=False)
  File "C:\python\lib\site-packages\instapy\instapy.py", line 319, in __init__
    self.logger,
  File "C:\python\lib\site-packages\instapy\browser.py", line 114, in set_selenium_local_session
    options=firefox_options,
  File "C:\python\lib\site-packages\selenium\webdriver\firefox\webdriver.py", line 174, in __init__
    keep_alive=True)
  File "C:\python\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "C:\python\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "C:\python\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\python\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: Unable to find a matching set of capabilities

Press any key to continue . . .

**Comment by Badmotheruk** [comment]
I have the same issue as above - please advise - i have latest install for firefox and chrome - geckodrive installed and python 3.8.2

**Comment by aitelkob** [comment]
same problem any of you guys found solution @Badmotheruk @ajith468
