### ISSUE TITLE
trying to run quick start 

### ISSUE THREAD

**Issue by sosetech** [InstaPy/instapy-quickstart#148]
Trying to run InstaPy start and i keep getting this error message 
InstaPy Version: 0.6.8
 ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.
Workspace in use: "C:/Users/hp/InstaPy"
Traceback (most recent call last):
  File "../quickstart.py", line 22, in <module>
    session = InstaPy(username=insta_username,
  File "C:\Users\hp\AppData\Local\Programs\Python\Python38-32\lib\site-packages\instapy\instapy.py", line 309, in __init__
    self.browser, err_msg = set_selenium_local_session(
  File "C:\Users\hp\AppData\Local\Programs\Python\Python38-32\lib\site-packages\instapy\browser.py", line 111, in set_selenium_local_session
    browser = webdriver.Firefox(
  File "C:\Users\hp\AppData\Local\Programs\Python\Python38-32\lib\site-packages\selenium\webdriver\firefox\webdriver.py", line 170, in __init__
    RemoteWebDriver.__init__(
  File "C:\Users\hp\AppData\Local\Programs\Python\Python38-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "C:\Users\hp\AppData\Local\Programs\Python\Python38-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "C:\Users\hp\AppData\Local\Programs\Python\Python38-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\hp\AppData\Local\Programs\Python\Python38-32\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: Unable to find a matching set of capabilities

**Comment by Badmotheruk** [comment]
I have the same issue as above - please advise - i have latest install for firefox and chrome - geckodrive installed and python 3.8.2

**Comment by spottico** [comment]
same here. dunno what i'm doing wrong

**Comment by boydthomson** [comment]
I had the same issue.  SSH to your server with ssh -CX user@host.  Run python3 quickstart, or whatever script you're running without using headless mode.  This will get you past whatever is holding up your script/cookie issue.

**Comment by Radu-K** [comment]
Same here. I’m using Pycharm . The installation is pretty straight forward . I tried change location and even created new project with all the files. Instapy filers are installed in site-package library. When run quickstart.py in the same lib just get errors for webdriver

**Comment by AffParo** [comment]
make sure your geckodriver is the correct version (32/64), add a path (https://www.softwaretestinghelp.com/geckodriver-selenium-tutorial/):


On Windows system right click on My Computer or This PC.
Select Properties.
Select advanced system settings.
Click on the Environment Variables button.
From System Variables select PATH.
Click on Edit button.
Click New button
Paste the path of GeckoDriver file.
 (I guess: C:\Users\XX\InstaPy\assets)
Click OK.
Restart your pc

**Comment by azeem1234567890** [comment]
having the same issue...please and resolve

**Comment by Hollywd** [comment]
This f InstaPy is so Buggy. I faced a lot of errors even during installation. 
Already downgraded Python to 3.6 to overcome several issues. And now this. F, author, programming is just not yours.

**Comment by newborngeek** [comment]
Workspace in use: "/Users/*************/InstaPy"
Traceback (most recent call last):
  File "/Users/*************/Desktop/Instabot/instapy1.py", line 11, in <module>
    session = InstaPy(username=insta_username,
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/instapy/instapy.py", line 325, in __init__
    self.browser, err_msg = set_selenium_local_session(
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/instapy/browser.py", line 123, in set_selenium_local_session
    browser = webdriver.Firefox(
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/selenium/webdriver/firefox/webdriver.py", line 170, in __init__
    RemoteWebDriver.__init__(
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: newSession
