### ISSUE TITLE
Getting timeout error

### ISSUE THREAD

**Issue by HackersSpirit** [InstaPy/instapy-quickstart#164]
I am trying to run the following example:
basic_follow-unfollow_activity.py

When the code in trying to fetch the user data the code crashes with following error:

Traceback (most recent call last):
  File "followUnfollow.py", line 40, in <module>
    session.follow_user_followers(['ternamemes'],
  File "\python\bot\.venv\lib\site-packages\instapy\instapy.py", line 3454, in follow_user_followers
    person_list, simulated_list = get_given_user_followers(
  File "\python\bot\.venv\lib\site-packages\instapy\unfollow_util.py", line 1013, in get_given_user_followers
    person_list, simulated_list = get_users_through_dialog_with_graphql(
  File "\python\bot\.venv\lib\site-packages\instapy\unfollow_util.py", line 767, in get_users_through_dialog_with_graphql
    browser.get("view-source:{}".format(url))
  File "\python\bot\.venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "\python\bot\.venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "\python\bot\.venv\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: Timeout loading page after 300000ms

**Comment by HackersSpirit** [comment]
Can we delete the issue found similar issue thread:
https://github.com/timgrossmann/InstaPy/issues/5404
