### ISSUE TITLE
Line 22 webdriver

### ISSUE THREAD

**Issue by aitelkob** [InstaPy/instapy-quickstart#175]
starting instapy with quickstart
================================
InstaPy Version: 0.6.10
 ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.
Workspace in use: "C:/Users/aitko/InstaPy"
Traceback (most recent call last):
  File "../quickstart.py", line 22, in <module>
    session = InstaPy(username='user',
  File "C:\Users\aitko\AppData\Local\Programs\Python\Python38-32\lib\site-packages\instapy-0.6.10-py3.8.egg\instapy\instapy.py", line 312, in __init__
    self.browser, err_msg = set_selenium_local_session(
  File "C:\Users\aitko\AppData\Local\Programs\Python\Python38-32\lib\site-packages\instapy-0.6.10-py3.8.egg\instapy\browser.py", line 121, in set_selenium_local_session
    browser = webdriver.Firefox(
  File "C:\Users\aitko\AppData\Local\Programs\Python\Python38-32\lib\site-packages\selenium\webdriver\firefox\webdriver.py", line 170, in __init__
    RemoteWebDriver.__init__(
  File "C:\Users\aitko\AppData\Local\Programs\Python\Python38-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "C:\Users\aitko\AppData\Local\Programs\Python\Python38-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "C:\Users\aitko\AppData\Local\Programs\Python\Python38-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\aitko\AppData\Local\Programs\Python\Python38-32\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: Unable to find a matching set of capabilities

Press any key to continue . . .

**Comment by Easyside** [comment]
**same** probleme!
