### ISSUE TITLE
Instapy not working

### ISSUE THREAD

**Issue by Aakash132** [InstaPy/instapy-quickstart#181]
C:\Users\Dell\Desktop>python quickstart.py
InstaPy Version: 0.6.10
 ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.
Workspace in use: "C:/Users/Dell/InstaPy"
Traceback (most recent call last):
  File "quickstart.py", line 12, in <module>
    session = InstaPy(username=insta_username,
  File "C:\Users\Dell\AppData\Local\Programs\Python\Python38-32\lib\site-packages\instapy\instapy.py", line 312, in __init__
    self.browser, err_msg = set_selenium_local_session(
  File "C:\Users\Dell\AppData\Local\Programs\Python\Python38-32\lib\site-packages\instapy\browser.py", line 121, in set_selenium_local_session
    browser = webdriver.Firefox(
  File "C:\Users\Dell\AppData\Local\Programs\Python\Python38-32\lib\site-packages\selenium\webdriver\firefox\webdriver.py", line 170, in __init__
    RemoteWebDriver.__init__(
  File "C:\Users\Dell\AppData\Local\Programs\Python\Python38-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "C:\Users\Dell\AppData\Local\Programs\Python\Python38-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "C:\Users\Dell\AppData\Local\Programs\Python\Python38-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Dell\AppData\Local\Programs\Python\Python38-32\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: Unable to find a matching set of capabilities

**Comment by streamkiller** [comment]
I got exactly the same issue, please help

**Comment by melnikovic** [comment]
Same issue here as well

**Comment by rererered** [comment]
same issue

**Comment by Damar404** [comment]
Same issue, what to do ?

**Comment by ermkmandawar** [comment]
@Aakash132 @Damar404 @rererered @melnikovic @streamkiller @
Download Firefox to use it. Its required.

**Comment by melnikovic** [comment]
> @Aakash132 @Damar404 @rererered @melnikovic @streamkiller @
> Download Firefox to use it. Its required.

With which version it will work?

**Comment by ermkmandawar** [comment]
> > @Aakash132 @Damar404 @rererered @melnikovic @streamkiller @
> > Download Firefox to use it. Its required.
> 
> With which version it will work?

It's work with the latest version
