### ISSUE TITLE
Error Running the quickstart.py

### ISSUE THREAD

**Issue by MusheAbdulHakim** [InstaPy/instapy-quickstart#184]
Traceback (most recent call last):                                                                                                            File "quickstart.py", line 22, in <module>                                                                                                    session = InstaPy(username=insta_username,                                                                                                File "C:\Users\mushe\AppData\Local\Programs\Python\Python38-32\lib\site-packages\instapy\instapy.py", line 312, in __init__                   self.browser, err_msg = set_selenium_local_session(                                                                                       File "C:\Users\mushe\AppData\Local\Programs\Python\Python38-32\lib\site-packages\instapy\browser.py", line 121, in set_selenium_local_session                                                                                                                                             browser = webdriver.Firefox(                                                                                                              File "C:\Users\mushe\AppData\Local\Programs\Python\Python38-32\lib\site-packages\selenium\webdriver\firefox\webdriver.py", line 170, in __init__                                                                                                                                          RemoteWebDriver.__init__(                                                                                                                 File "C:\Users\mushe\AppData\Local\Programs\Python\Python38-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 157, in __init__                                                                                                                                           self.start_session(capabilities, browser_profile)                                                                                         File "C:\Users\mushe\AppData\Local\Programs\Python\Python38-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 252, in start_session                                                                                                                                      response = self.execute(Command.NEW_SESSION, parameters)                                                                                  File "C:\Users\mushe\AppData\Local\Programs\Python\Python38-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute                                                                                                                                            self.error_handler.check_response(response)                                                                                               File "C:\Users\mushe\AppData\Local\Programs\Python\Python38-32\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response                                                                                                                                  raise exception_class(message, screen, stacktrace)                                                                                      selenium.common.exceptions.SessionNotCreatedException: Message: Unable to find a matching set of capabilities

**Comment by rererered** [comment]
same issue here

**Comment by Damar404** [comment]
same

**Comment by GehadSalemFekry** [comment]
same
