### ISSUE TITLE
Error, unable to determine correct filename for 64bit linux

### ISSUE THREAD

**Issue by debeast7** [InstaPy/instapy-quickstart#185]
Hello! I'm facing this issue whenever i enter this command "python3 quickstart.py". Can someone tell me the solution.
InstaPy Version: 0.6.10
 ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._. 
Workspace in use: "/home/debeast7/InstaPy"
Error, unable to determine correct filename for 64bit linux
Traceback (most recent call last):
  File "quickstart.py", line 22, in <module>
    session = InstaPy(username=insta_username,
  File "/home/debeast7/.local/lib/python3.8/site-packages/instapy/instapy.py", line 312, in __init__
    self.browser, err_msg = set_selenium_local_session(
  File "/home/debeast7/.local/lib/python3.8/site-packages/instapy/browser.py", line 120, in set_selenium_local_session
    driver_path = geckodriver_path or get_geckodriver()
  File "/home/debeast7/.local/lib/python3.8/site-packages/instapy/browser.py", line 36, in get_geckodriver
    sym_path = gdd.download_and_install()[1]
  File "/home/debeast7/.local/lib/python3.8/site-packages/webdriverdownloader/webdriverdownloader.py", line 174, in download_and_install
    filename_with_path = self.download(version,
  File "/home/debeast7/.local/lib/python3.8/site-packages/webdriverdownloader/webdriverdownloader.py", line 129, in download
    download_url = self.get_download_url(version, os_name=os_name, bitness=bitness)
  File "/home/debeast7/.local/lib/python3.8/site-packages/webdriverdownloader/webdriverdownloader.py", line 324, in get_download_url
    raise RuntimeError(info_message)
RuntimeError: Error, unable to determine correct filename for 64bit linux

**Comment by Braslerl** [comment]
same here

**Comment by aldotoci** [comment]
Same here

**Comment by nandoschneider** [comment]
same here

**Comment by kron-spar** [comment]
Had the same here on ubuntu 20.04 LTS. The issue isnt with instapy, it was with the webdriverdownloader.py. I ran 
```bash
sudo apt install firefox-geckodriver
```
And that fixed it for me. Hope this works for you all!

**Comment by robertgagnon726** [comment]
> Had the same here on ubuntu 20.04 LTS. The issue isnt with instapy, it was with the webdriverdownloader.py. I ran
> 
> ```shell
> sudo apt install firefox-geckodriver
> ```
> 
> And that fixed it for me. Hope this works for you all!

This fixed it for me as well. Thanks!
