### ISSUE TITLE
Unable to find a matching set of capabilities

### ISSUE THREAD

**Issue by tommyyama2020** [InstaPy/instapy-quickstart#188]

**Comment by tommyyama2020** [comment]
Sorry for bothering the author. It seems worked and closing now. Same issues opened yet could be closed till now.

![Screen Shot 2020-09-19 at 15 57 28](https://user-images.githubusercontent.com/38548157/93661200-e1474380-fa90-11ea-9b9c-6952125fec96.png)

**Comment by tommyyama2020** [comment]
As long as i remember,  downloaded driver and mozilla on linux and fixed.
Hope this will be implemented in the future.  
https://github.com/mozilla/geckodriver/releases

**Comment by tommyyama2020** [comment]
Hi folks, FYI  no guarantee for others using different env, tho.

**Comment by realshantanu** [comment]
C:\Users\Shantanu\Desktop\EDITH\instapy-quickstart-master>python quickstart.py
InstaPy Version: 0.6.11
 ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.
Workspace in use: "C:/Users/Shantanu/InstaPy"
Traceback (most recent call last):
  File "quickstart.py", line 22, in <module>
    session = InstaPy(username=insta_username,
  File "C:\Users\Shantanu\AppData\Local\Programs\Python\Python38-32\lib\site-packages\instapy\instapy.py", line 321, in __init__
    self.browser, err_msg = set_selenium_local_session(
  File "C:\Users\Shantanu\AppData\Local\Programs\Python\Python38-32\lib\site-packages\instapy\browser.py", line 126, in set_selenium_local_session
    browser = webdriver.Firefox(
  File "C:\Users\Shantanu\AppData\Local\Programs\Python\Python38-32\lib\site-packages\selenium\webdriver\firefox\webdriver.py", line 170, in __init__
    RemoteWebDriver.__init__(
  File "C:\Users\Shantanu\AppData\Local\Programs\Python\Python38-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "C:\Users\Shantanu\AppData\Local\Programs\Python\Python38-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "C:\Users\Shantanu\AppData\Local\Programs\Python\Python38-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Shantanu\AppData\Local\Programs\Python\Python38-32\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: Unable to find a matching set of capabilities

**Comment by tommyyama2020** [comment]
i used firebox after downloading the driver in linux. fixed as long as i remember.

**Comment by realshantanu** [comment]
which driver

**Comment by tommyyama2020** [comment]
geckodriver. just ask around and google the issue. you will find a way
