### ISSUE TITLE
name erroe

### ISSUE THREAD

**Issue by Protato-noob** [InstaPy/instapy-quickstart#189]
File "quickstart.py", line 22, in <module>
    session = InstaPy(username=ngrok_instafollowers,
NameError: name 'ngrok_instafollowers' is not defined

**Comment by kalathiyabhavik** [comment]
InstaPy(username="abcd", password="1234")

**Comment by Protato-noob** [comment]
> 
> 
> InstaPy(username="abcd", password="1234")

Workspace in use: "/root/InstaPy"
Error, unable to determine correct filename for 64bit linux
Traceback (most recent call last):
  File "quickstart.py", line 5, in <module>
    session = InstaPy(username='ngrok_instafollowers', password='Jainyash88')
  File "/usr/local/lib/python3.8/dist-packages/instapy/instapy.py", line 312, in __init__
    self.browser, err_msg = set_selenium_local_session(
  File "/usr/local/lib/python3.8/dist-packages/instapy/browser.py", line 120, in set_selenium_local_session
    driver_path = geckodriver_path or get_geckodriver()
  File "/usr/local/lib/python3.8/dist-packages/instapy/browser.py", line 36, in get_geckodriver
    sym_path = gdd.download_and_install()[1]
  File "/usr/local/lib/python3.8/dist-packages/webdriverdownloader/webdriverdownloader.py", line 174, in download_and_install
    filename_with_path = self.download(version,
  File "/usr/local/lib/python3.8/dist-packages/webdriverdownloader/webdriverdownloader.py", line 129, in download
    download_url = self.get_download_url(version, os_name=os_name, bitness=bitness)
  File "/usr/local/lib/python3.8/dist-packages/webdriverdownloader/webdriverdownloader.py", line 324, in get_download_url
    raise RuntimeError(info_message)
RuntimeError: Error, unable to determine correct filename for 64bit linux

**Comment by kron-spar** [comment]
Had the same here on ubuntu 20.04 LTS. The issue isnt with instapy, it was with the webdriverdownloader.py. I ran 
```bash
sudo apt install firefox-geckodriver
```
And that fixed it for me.

**Comment by tommyyama2020** [comment]
maybe the author can implement this driver's installation in install file.
