### ISSUE TITLE
cannot run quickstart

### ISSUE THREAD

**Issue by dboycool** [InstaPy/instapy-quickstart#190]
Workspace in use: "C:/Users/oarmt/InstaPy"
Traceback (most recent call last):
  File "C:\Users\oarmt\Downloads\instapy-quickstart-master\quickstart_templates\basic_follow-unfollow_activity.py", line 30, in <module>
    session = InstaPy(username=insta_username,
  File "C:\Users\oarmt\AppData\Local\Programs\Python\Python38-32\lib\site-packages\instapy\instapy.py", line 321, in __init__
    self.browser, err_msg = set_selenium_local_session(
  File "C:\Users\oarmt\AppData\Local\Programs\Python\Python38-32\lib\site-packages\instapy\browser.py", line 126, in set_selenium_local_session
    browser = webdriver.Firefox(
  File "C:\Users\oarmt\AppData\Local\Programs\Python\Python38-32\lib\site-packages\selenium\webdriver\firefox\webdriver.py", line 170, in __init__
    RemoteWebDriver.__init__(
  File "C:\Users\oarmt\AppData\Local\Programs\Python\Python38-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "C:\Users\oarmt\AppData\Local\Programs\Python\Python38-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "C:\Users\oarmt\AppData\Local\Programs\Python\Python38-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\oarmt\AppData\Local\Programs\Python\Python38-32\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: Unable to find a matching set of capabilities

**Comment by stephenrischall** [comment]
I am having the same issue. I've confirmed the latest version of Python is installed and can run that. Also confirmed that InstPy is installed and up to date. I go the the quickstart file, add my credentials, but can't actually get the session to open a chrome window and start.

I'm using a Windows 10 pro physical machine. Would it be better to create a VM in order to run IstaPy?

**Comment by Damar404** [comment]
same issue

**Comment by subhan97ahmed** [comment]
have you guys installed firefox? I had the same issue cause I forgot to install firefox

**Comment by aurel2222** [comment]
> 
> 
> have you guys installed firefox? I had the same issue cause I forgot to install firefox

hi, thanks for your answer. Firefox is installed on my computer. Is there something I missed ?

**Comment by lazcad-v** [comment]
Some use

**Comment by MCilento93** [comment]
Does firefox if stricktly required for selenium?

**Comment by ermkmandawar** [comment]
Firefox is required.
