### ISSUE TITLE
Issue running quickstart.py: DDL load failed

### ISSUE THREAD

**Issue by Atumos** [InstaPy/instapy-quickstart#195]
Hi guys

I've just installed instapy on my pc and tried to run the quickstart.py (which is located in \lib\site-packages\ foldeder). The code doesn't run and I get the following error: 

Traceback (most recent call last):
  File "C:\Users\atu\AppData\Local\Programs\Python\Python36\Lib\site-packages\quickstart.py", line 19, in <module>
    from instapy import InstaPy
  File "C:\Users\atu\AppData\Local\Programs\Python\Python36\Lib\site-packages\instapy\__init__.py", line 6, in <module>
    from .instapy import InstaPy
  File "C:\Users\atu\AppData\Local\Programs\Python\Python36\Lib\site-packages\instapy\instapy.py", line 30, in <module>
    from .clarifai_util import check_image
  File "C:\Users\atu\AppData\Local\Programs\Python\Python36\Lib\site-packages\instapy\clarifai_util.py", line 3, in <module>
    from clarifai.rest import ClarifaiApp
  File "C:\Users\atu\AppData\Local\Programs\Python\Python36\Lib\site-packages\clarifai\rest\__init__.py", line 3, in <module>
    from clarifai.rest.client import ApiClient
  File "C:\Users\atu\AppData\Local\Programs\Python\Python36\Lib\site-packages\clarifai\rest\client.py", line 23, in <module>
    from google.protobuf.struct_pb2 import Struct
  File "C:\Users\atu\AppData\Local\Programs\Python\Python36\Lib\site-packages\google\protobuf\struct_pb2.py", line 6, in <module>
    from google.protobuf import descriptor as _descriptor
  File "C:\Users\atu\AppData\Local\Programs\Python\Python36\Lib\site-packages\google\protobuf\descriptor.py", line 48, in <module>
    from google.protobuf.pyext import _message
ImportError: DLL load failed: The specified procedure was not found.
>>> 

Does anyone know how to solve this issue?

**Comment by Atumos** [comment]
Solved: I've needed an older version (Python 3.7).
