### ISSUE TITLE
Cannot log in

### ISSUE THREAD

**Issue by ntelo007** [InstaPy/instapy-quickstart#198]
Good evening,

I am trying to use one of the quick-start templates and I am receiving the following error:

```
(env name) username@username-ubuntu:~/Documents/python_projects/InstaPy$ python my_quickstart.py 
InstaPy Version: 0.6.11
 ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._. 
Workspace in use: "/home/username/InstaPy"
OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
INFO [2020-10-29 15:38:27] [account_name]  Session started!
oooooooooooooooooooooooooooooooooooooooooooooooooooooo
INFO [2020-10-29 15:38:27] [account_name]  -- Connection Checklist [1/2] (Internet Connection Status)
INFO [2020-10-29 15:38:27] [account_name]  - Internet Connection Status: ok
INFO [2020-10-29 15:38:27] [account_name]  - Current IP is "31.21.111.143" and it's from "Netherlands/NL"
INFO [2020-10-29 15:38:27] [account_name]  -- Connection Checklist [2/2] (Hide Selenium Extension)
INFO [2020-10-29 15:38:28] [account_name]  - window.navigator.webdriver response: None
INFO [2020-10-29 15:38:28] [account_name]  - Hide Selenium Extension: ok
Cookie file not found, creating cookie...
INFO [2020-10-29 15:39:08] [account_name]  Timed out with failure while explicitly waiting until title contains 'Login' string!

INFO [2020-10-29 15:39:46] [account_name]  Timed out with failure while explicitly waiting until visibility of element located!

**********************************************************************
If raising an issue, please also upload the file located at:
/tmp/20201029-153951.html
**********************************************************************

INFO [2020-10-29 15:39:52] [account_name]  Sessional Live Report:
	|> No any statistics to show


[Session lasted 1.46 minutes]
OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
INFO [2020-10-29 15:39:52] [account_name]  Session ended!
ooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo



Traceback (most recent call last):
  File "my_quickstart.py", line 34, in <module>
    with smart_run(session):
  File "/home/username/anaconda3/envs/instaplay/lib/python3.6/contextlib.py", line 83, in __enter__
    raise RuntimeError("generator didn't yield") from None
RuntimeError: generator didn't yield
```

**Comment by lyubchev** [comment]
Same here

**Comment by pooja-anandani** [comment]
Please try this 

insta_session = InstaPy(username=instagram_username,
                        password=instagram_password, headless_browser=False)
insta_session.login()

**Comment by fgadaleta** [comment]
`Cookie file not found, creating cookie...`
and it stays there until timeout and 

```
Traceback (most recent call last):
  File "main.py", line 35, in <module>
    session.login()
  File "/home/frag/miniconda3/envs/dev/lib/python3.8/site-packages/instapy/instapy.py", line 425, in login
    if not login_user(
  File "/home/frag/miniconda3/envs/dev/lib/python3.8/site-packages/instapy/login_util.py", line 316, in login_user
    input_username = browser.find_element_by_xpath(input_username_XP)
  File "/home/frag/miniconda3/envs/dev/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "/home/frag/miniconda3/envs/dev/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 976, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "/home/frag/miniconda3/envs/dev/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/frag/miniconda3/envs/dev/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: //input[@name='username']
```

Seems like login has changed
