### ISSUE TITLE
Some assistance with the code please?

### ISSUE THREAD

**Issue by argyangelop** [InstaPy/instapy-quickstart#200]
Could you please help me understand what the issue with the code bellow is?

I have installed it, set the username/password and tried to run the most basic version to see if it works. 
I open it with IDLE and then press F5 to run and then this:

```
Traceback (most recent call last):
  File "C:\Users\argya\Documents\instapy-quickstart-master\quickstart_templates\basic_follow-unfollow_activity.py", line 30, in <module>
    session = InstaPy(username=insta_username,
  File "C:\Users\argya\AppData\Local\Programs\Python\Python38-32\lib\site-packages\instapy\instapy.py", line 322, in __init__
    self.browser, err_msg = set_selenium_local_session(
  File "C:\Users\argya\AppData\Local\Programs\Python\Python38-32\lib\site-packages\instapy\browser.py", line 132, in set_selenium_local_session
    browser = webdriver.Firefox(
  File "C:\Users\argya\AppData\Local\Programs\Python\Python38-32\lib\site-packages\selenium\webdriver\firefox\webdriver.py", line 170, in __init__
    RemoteWebDriver.__init__(
  File "C:\Users\argya\AppData\Local\Programs\Python\Python38-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "C:\Users\argya\AppData\Local\Programs\Python\Python38-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "C:\Users\argya\AppData\Local\Programs\Python\Python38-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\argya\AppData\Local\Programs\Python\Python38-32\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: Unable to find a matching set of capabilities
```

**Comment by aurel2222** [comment]
Hi all,
I have exactly the same problem....
I tried many quickstart scripts... same thing.

I tried then :
`insta_username = "myusername"`
or
`insta_username = 'myusername'`
or
`insta_username = myusername`

Any time and help will be appreciated  :)

thanks !

EDIT : just have to put forefox driver into main directory of project :/ so ....
