### ISSUE TITLE
I just installed INSTAPY on Kali Linux Amd64 and is not working

### ISSUE THREAD

**Issue by zonacero541** [InstaPy/instapy-quickstart#203]
I installed INSTAPY by the command:

$ pip3 install instapy
then I downloaded the quickstart and when to Linux install

$chmod 777 install and update
and then run the scripts
have one red status:

ERROR: After October 2020 you may experience errors when installing or updating packages. This is because pip will change the way that it resolves dependency conflicts.          
                                                                                         
We recommend you use --use-feature=2020-resolver to test your packages with the new resolver before it becomes the default.                                                       
                                                                                         
clarifai 2.6.2 requires configparser<4,>=3.5, but you'll have configparser 5.0.1 which is incompatible.  

THEN I chmod the run linux file and run it (nothing happened)
FINALLY run the quickstart changing the username and password and headless TRUE and got this:

└─$ python3 quickstart.py                                                            1 ⨯
InstaPy Version: 0.6.12
 ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._. 
Workspace in use: "/home/zara/InstaPy"
Error, unable to determine correct filename for 64bit linux
Traceback (most recent call last):
  File "quickstart.py", line 13, in <module>
    session = InstaPy(username=insta_username,
  File "/home/zara/.local/lib/python3.8/site-packages/instapy/instapy.py", line 322, in __init__
    self.browser, err_msg = set_selenium_local_session(
  File "/home/zara/.local/lib/python3.8/site-packages/instapy/browser.py", line 131, in set_selenium_local_session
    driver_path = geckodriver_path or get_geckodriver()
  File "/home/zara/.local/lib/python3.8/site-packages/instapy/browser.py", line 38, in get_geckodriver
    sym_path = gdd.download_and_install()[1]
  File "/home/zara/.local/lib/python3.8/site-packages/webdriverdownloader/webdriverdownloader.py", line 174, in download_and_install
    filename_with_path = self.download(version,
  File "/home/zara/.local/lib/python3.8/site-packages/webdriverdownloader/webdriverdownloader.py", line 129, in download
    download_url = self.get_download_url(version, os_name=os_name, bitness=bitness)
  File "/home/zara/.local/lib/python3.8/site-packages/webdriverdownloader/webdriverdownloader.py", line 324, in get_download_url
    raise RuntimeError(info_message)
RuntimeError: Error, unable to determine correct filename for 64bit linux

**Comment by ghost** [comment]
I had the same issue 
Just Start a fresh linux installation 
And follow the video tutorial 

"pip install instapy" isnt working

Chers 

Edit.
Maybe this help


Had the same here on ubuntu 20.04 LTS. The issue isnt with instapy, it was with the webdriverdownloader.py. I ran

sudo apt install firefox-geckodriver

And that fixed it for me. Hope this works for you all!
