### ISSUE TITLE
Ububtu 18.04(64 Bit) server new instance 

### ISSUE THREAD

**Issue by orassr** [InstaPy/instapy-quickstart#205]
Python version: 3.6.9
pip 20.3 installed
google chrome version 87.0.42680.66
firefox and firefoxdriver installed as well

```
# imports
from instapy import InstaPy
from instapy import smart_run

# login credentials
insta_username = 'username'
insta_password = 'password'

comments = ['Nice shot! @{}',
        'I love your profile! @{}',
        'Your feed is an inspiration :thumbsup:',
        'Just incredible :open_mouth:',
        'What camera did you use @{}?',
        'Love your posts @{}',
        'Looks awesome @{}',
        'Getting inspired by you @{}',
        ':raised_hands: Yes!',
        'I can feel your passion @{} :muscle:']

# get an InstaPy session!
# set headless_browser=True to run InstaPy in the background
session = InstaPy(username=insta_username,
                  password=insta_password,
                  headless_browser=False)

with smart_run(session):
  """ Activity flow """
  # general settings
  session.set_dont_include(["friend1", "friend2", "friend3"])

  # activity
  session.like_by_tags(["natgeo"], amount=10)

  # Joining Engagement Pods
  session.set_do_comment(enabled=True, percentage=35)
  session.set_comments(comments)
  session.join_pods(topic='sports', engagement_mode='no_comments')
```

python3 quickstart.py
```

InstaPy Version: 0.6.12
 ._.  ._.  ._.  ._.  ._.  ._.  ._.
Workspace in use: "/root/InstaPy"
Traceback (most recent call last):
  File "quickstartnew.py", line 25, in <module>
    headless_browser=False)
  File "/usr/local/lib/python3.6/dist-packages/instapy/instapy.py", line 335, in __init__
    geckodriver_log_level,
  File "/usr/local/lib/python3.6/dist-packages/instapy/browser.py", line 136, in set_selenium_local_session
    options=firefox_options,
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/firefox/webdriver.py", line 174, in __init__
    keep_alive=True)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: Process unexpectedly closed with status 1
```

**Comment by elulcao** [comment]
Google Chrome has been deprecated
google chrome version 87.0.42680.66


Use FireFox,
