### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by jt7777777** [InstaPy/instapy-quickstart#216]
When I try to run script for installing bot i always get this error can somebody help please: 

SyntaxError: invalid syntax
There was a problem installing InstaPy, please copy the error message and create an issue here: https://github.com/InstaPy/instapy-quickstart/issues

Full logs: 

Last login: Fri Jan 29 22:44:06 on ttys000

The default interactive shell is now zsh.
To update your account to use zsh, please run `chsh -s /bin/zsh`.
For more details, please visit https://support.apple.com/kb/HT208050.
/Users/jakubtabak/Downloads/instapy-quickstart-master/installation/MacOs/install.command ; exit;
MacBook-Pro-uzivatela-Jakub:~ jakubtabak$ /Users/jakubtabak/Downloads/instapy-quickstart-master/installation/MacOs/install.command ; exit;
/Users/jakubtabak/Downloads/instapy-quickstart-master/installation/MacOs/install.command: line 3: [: !=: unary operator expected
Python is installed
====================
Pip is installed
====================
Chrome is installed
====================
Installing InstaPy...
Traceback (most recent call last):
  File "/usr/local/bin/pip", line 11, in <module>
    load_entry_point('pip==21.0', 'console_scripts', 'pip')()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 2843, in load_entry_point
    return ep.load()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 2434, in load
    return self.resolve()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 2440, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/Library/Python/2.7/site-packages/pip-21.0-py2.7.egg/pip/_internal/cli/main.py", line 60
    sys.stderr.write(f"ERROR: {exc}")
                                   ^
SyntaxError: invalid syntax
====================
Traceback (most recent call last):
  File "/usr/local/bin/pip", line 11, in <module>
    load_entry_point('pip==21.0', 'console_scripts', 'pip')()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 2843, in load_entry_point
    return ep.load()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 2434, in load
    return self.resolve()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 2440, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/Library/Python/2.7/site-packages/pip-21.0-py2.7.egg/pip/_internal/cli/main.py", line 60
    sys.stderr.write(f"ERROR: {exc}")
                                   ^
SyntaxError: invalid syntax
There was a problem installing InstaPy, please copy the error message and create an issue here: https://github.com/InstaPy/instapy-quickstart/issues

You can also manually install InstaPy with this guide: https://github.com/timgrossmann/InstaPy

Sorry for the inconveniences
logout
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

[Proces dokončený]

**Comment by jt7777777** [comment]
I also tried execute: pip install instapy but also get error: 

Last login: Fri Jan 29 22:45:09 on ttys000

The default interactive shell is now zsh.
To update your account to use zsh, please run `chsh -s /bin/zsh`.
For more details, please visit https://support.apple.com/kb/HT208050.
MacBook-Pro-uzivatela-Jakub:~ jakubtabak$ pip install instapy
Traceback (most recent call last):
  File "/usr/local/bin/pip", line 11, in <module>
    load_entry_point('pip==21.0', 'console_scripts', 'pip')()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 2843, in load_entry_point
    return ep.load()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 2434, in load
    return self.resolve()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 2440, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/Library/Python/2.7/site-packages/pip-21.0-py2.7.egg/pip/_internal/cli/main.py", line 60
    sys.stderr.write(f"ERROR: {exc}")
                                   ^
SyntaxError: invalid syntax

**Comment by kotya341** [comment]
do you have any update, how to solve this issue?

**Comment by jayjay992** [comment]
this issue is very annoying

**Comment by jayjay992** [comment]
![Screen Shot 2021-12-05 at 4 56 36 PM](https://user-images.githubusercontent.com/95319921/144765578-193008c8-ff5c-4556-9390-abda9d52b9f7.png)

<br>

![Screen Shot 2021-12-05 at 4 56 24 PM](https://user-images.githubusercontent.com/95319921/144765580-8c447cb7-bc63-4ce3-8dbb-59c35a78fa36.png)
)
