### ISSUE TITLE
Error, unable to determine correct filename for 64bit macos

### ISSUE THREAD

**Issue by rimager** [InstaPy/instapy-quickstart#239]
instapy-quickstart-master % python3 quickstart.py
InstaPy Version: 0.6.13
 ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._. 
Workspace in use: "/Users/rimagerhard/InstaPy"
Error, unable to determine correct filename for 64bit macos
Traceback (most recent call last):
  File "/Users/rimagerhard/Downloads/instapy-quickstart-master/quickstart.py", line 22, in <module>
    session = InstaPy(username=insta_username,
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/instapy/instapy.py", line 325, in __init__
    self.browser, err_msg = set_selenium_local_session(
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/instapy/browser.py", line 122, in set_selenium_local_session
    driver_path = geckodriver_path or get_geckodriver()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/instapy/browser.py", line 38, in get_geckodriver
    sym_path = gdd.download_and_install()[1]
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/webdriverdownloader/webdriverdownloader.py", line 174, in download_and_install
    filename_with_path = self.download(version,
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/webdriverdownloader/webdriverdownloader.py", line 129, in download
    download_url = self.get_download_url(version, os_name=os_name, bitness=bitness)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/webdriverdownloader/webdriverdownloader.py", line 324, in get_download_url
    raise RuntimeError(info_message)
RuntimeError: Error, unable to determine correct filename for 64bit macos

**Comment by izlatkin** [comment]
I have the same issue. How to workaround this? Where we should put driver?

**Comment by thebadcoder96** [comment]
I had the same issue and found that you have to install geckodriver for firebox to fix this.

I just used ``` brew install geckodriver ```

**Comment by lextale** [comment]
I had the same problem.

**Explanation**
```
The reason is that the code in the webdriverdownloader dependency, wich gets the list of possible geckodriver versions to download and then filters for the ones that match your os and if it is 32 or 64 bit. Then it expects to have only one left in the list, wich it downloads. Turns out there are 2 now, with 2 extensions(something like '.tar.gz' and '.tar.gz.asc'). So the solution is to remove one of them so that we don't fall on the exception.
The one we want to remove is the one that ends on .asc cause apparently the program is expecting the other one
```

**Solution**
> https://github.com/timgrossmann/InstaPy/issues/5672
>https://github.com/leonidessaguisagjr/webdriverdownloader/pull/12
>https://github.com/leonidessaguisagjr/webdriverdownloader/commit/a47a57c3a3ff20d81178989149946b6c128d46c8

**Summary**
You just have to find where webdriverdownloader.py is stored and change the line 320 into:
`filename = [name for name in filenames if os_name + bitness in name and name[-3:] != 'asc' ]`

**Comment by paul109** [comment]
@lextale 

This does not work for me. 

I still get the same error. 

Do you have any idea how I could solve this.

Thanks in advance!

**Comment by Ibrahim-011** [comment]
apple@apples-MacBook-Pro ~ % brew install geckodriver
Running `brew update --auto-update`...
fatal: Could not resolve HEAD to a revision
Warning: No available formula with the name "geckodriver".
==> Searching for similarly named formulae...
Error: No similarly named formulae found.
==> Searching for a previously deleted formula (in the last month)...
Error: No previously deleted formula found.
==> Searching taps on GitHub...
Error: No formulae found in taps.

**Comment by kurtesy** [comment]
I tried `brew install geckodriver` and this resolved the above issue atleast
