### ISSUE TITLE
Time out

### ISSUE THREAD

**Issue by Jostino** [InstaPy/instapy-quickstart#240]
Just updated Instapy, but this is the result

```
OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
INFO [2021-07-14 10:37:38] [username]  Session started!
oooooooooooooooooooooooooooooooooooooooooooooooooooooo
INFO [2021-07-14 10:37:39] [username]  -- Connection Checklist [1/2] (Internet Connection Status)
INFO [2021-07-14 10:37:40] [username]  - Internet Connection Status: ok
INFO [2021-07-14 10:37:40] [username]  - Current IP is "x.x.x.x" and it's from "Italy/IT"
INFO [2021-07-14 10:37:40] [username]  -- Connection Checklist [2/2] (Hide Selenium Extension)
INFO [2021-07-14 10:37:40] [username]  - window.navigator.webdriver response: None
INFO [2021-07-14 10:37:40] [username]  - Hide Selenium Extension: ok
INFO [2021-07-14 10:37:46] [username]  - Cookie file not found, creating cookie...
INFO [2021-07-14 10:38:26] [username]  Timed out with failure while explicitly waiting until visibility of element located!

**********************************************************************
If raising an issue, please also upload the file located at:
/tmp/20210714-103831.html
**********************************************************************

INFO [2021-07-14 10:38:33] [username]  Sessional Live Report:
	|> No any statistics to show


[Session lasted 1.14 minutes]
OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
INFO [2021-07-14 10:38:33] [username]  Session ended!
ooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo



Traceback (most recent call last):
  File "/home/pi/InstaPy/assets/script.py", line 34, in <module>
    with smart_run(session, threaded=True):
  File "/usr/lib/python3.7/contextlib.py", line 114, in __enter__
    raise RuntimeError("generator didn't yield") from None
RuntimeError: generator didn't yield

```

**Comment by Be55am** [comment]
any update ?
