### ISSUE TITLE
Cookies and selenium error :/

### ISSUE THREAD

**Issue by xxxjajoxxx** [InstaPy/instapy-quickstart#242]
```
INFO [2021-07-19 19:21:00] [xxx]  -- Connection Checklist [2/2] (Hide Selenium Extension)


INFO [2021-07-19 19:21:00] [xxx]  - window.navigator.webdriver response: True


WARNING [2021-07-19 19:21:00] [xxx]  - Hide Selenium Extension: error


INFO [2021-07-19 19:21:04] [xxx]  - Cookie file not found, creating cookie...


INFO [2021-07-19 19:21:44] [xxx]  Timed out with failure while explicitly waiting until visibility of element located!


INFO [2021-07-19 19:21:50] [sxxx]  Sessional Live Report:


	|> No any statistics to show


[Session lasted 57.84 seconds]


INFO [2021-07-19 19:21:50] [xxx]  Session ended!


Traceback (most recent call last):


  File "docker_quickstart.py", line 20, in <module>


    with smart_run(session):


  File "/usr/local/lib/python3.7/contextlib.py", line 114, in __enter__


    raise RuntimeError("generator didn't yield") from None


RuntimeError: generator didn't yield


InstaPy Version: 0.6.13


 ._.  ._.  ._.  ._.  ._.  ._.  ._. 


Workspace in use: "/code/InstaPy"


OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO


oooooooooooooooooooooooooooooooooooooooooooooooooooooo


**********************************************************************


If raising an issue, please also upload the file located at:


/tmp/20210719-192149.html


**********************************************************************


OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO


ooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo

```

Can someone help me?

**Comment by goproists** [comment]
You can check your configuration out, to validate if you are allowing coockies in your browser. Remember to use Firefox.
