### ISSUE TITLE
I can't run the bot on windows 10

### ISSUE THREAD

**Issue by tuliosousa25** [InstaPy/instapy-quickstart#25]
INFO [2019-04-22 20:49:54] [myusername]  Using built in instapy-chromedriver executable (version 2.44)
Traceback (most recent call last):
  File "E:\Área de Trabalho\InstaPy-master\quickstart.py", line 30, in <module>
    headless_browser=False)
  File "E:\Área de Trabalho\InstaPy-master\instapy\instapy.py", line 295, in __init__
    self.set_selenium_local_session()
  File "E:\Área de Trabalho\InstaPy-master\instapy\instapy.py", line 347, in set_selenium_local_session
    self.logger)
  File "E:\Área de Trabalho\InstaPy-master\instapy\browser.py", line 146, in set_selenium_local_session
    chrome_options=chrome_options)
  File "C:\Users\tulio\AppData\Local\Programs\Python\Python37-32\lib\site-packages\selenium\webdriver\chrome\webdriver.py", line 73, in __init__
    self.service.start()
  File "C:\Users\tulio\AppData\Local\Programs\Python\Python37-32\lib\site-packages\selenium\webdriver\common\service.py", line 76, in start
    stdin=PIPE)
  File "C:\Users\tulio\AppData\Local\Programs\Python\Python37-32\lib\subprocess.py", line 756, in __init__
    restore_signals, start_new_session)
  File "C:\Users\tulio\AppData\Local\Programs\Python\Python37-32\lib\subprocess.py", line 1155, in _execute_child
    startupinfo)
OSError: [WinError 740] A operação solicitada requer elevação

**Comment by timgrossmann** [comment]
@tuliosousa25 Please reopen this issue at the InstaPy main repo since this is non related to the quickstart files.
Thank you 😊
