### ISSUE TITLE
No idea please help

### ISSUE THREAD

**Issue by sector13ghost** [InstaPy/instapy-quickstart#251]
![image](https://user-images.githubusercontent.com/98127210/150432274-01d545db-56cc-4594-8bae-348f61061b46.png)
line 1980
![image](https://user-images.githubusercontent.com/98127210/150432322-27510398-83f4-4278-88e9-d38e771f1f23.png)
line 619
![image](https://user-images.githubusercontent.com/98127210/150432479-89f980bf-cef5-4f0c-9e4f-13ae111ca0d0.png)
Then all this and more i dont have a clue what is wrong im no expert ^^

Error occurs after clicking on a photo

**Comment by mikestan** [comment]
Having the same issue here within the past week or so - whenever the first image gets clicked the session ends and the following traceback occurs:

Traceback (most recent call last):
  File "/home/ubuntu/quickstart.py", line 60, in <module>
    session.like_by_tags(my_hashtags, amount=20, media=None, interact=True)
  File "/home/ubuntu/.local/lib/python3.9/site-packages/instapy/instapy.py", line 1980, in like_by_tags
    inappropriate, user_name, is_video, reason, scope = check_link(
  File "/home/ubuntu/.local/lib/python3.9/site-packages/instapy/like_util.py", line 619, in check_link
    media = post_page[0]["shortcode_media"]
KeyError: 0

Running instapy 0.6.16 headless on Ubuntu / RPi B+...

**Comment by omertacs** [comment]
I'm having the same issue. Session dies on the first image.

**Comment by dabudeveloper** [comment]
Same issue here, still happens.

**Comment by uvzz** [comment]
simple fix (please note that I ignored the owner_comments whatever it is):

in like_util.py line 619 remove these lines:

        media = post_page[0]["shortcode_media"]
        is_video = media["is_video"]
        user_name = media["owner"]["username"]
        image_text = media["caption"]

        owner_comments = browser.execute_script(
            """
            latest_comments = window._sharedData.entry_data.PostPage[
            0].media.comments.nodes;
            if (latest_comments === undefined) {
                latest_comments = Array();
                owner_comments = latest_comments
                    .filter(item => item.user.username == arguments[0])
                    .map(item => item.text)
                    .reduce((item, total) => item + '\\n' + total, '');
                return owner_comments;}
            else {
                return null;}
        """,
            user_name,
        )

    if owner_comments == "":
        owner_comments = None


and add this instead:

        '''
        original code:
        
        media = post_page[0]["shortcode_media"]
        is_video = media["is_video"]
        user_name = media["owner"]["username"]
        image_text = media["caption"]
        '''

        # fixed by uvzz
        media = post_page["items"][0]
        is_video = media["is_unified_video"]
        user_name = media["user"]["username"]
        image_text = media["caption"]["text"]

        '''
       commenting this out:

        owner_comments = browser.execute_script(
            """
            latest_comments = window._sharedData.entry_data.PostPage[
            0].media.comments.nodes;
            if (latest_comments === undefined) {
                latest_comments = Array();
                owner_comments = latest_comments
                    .filter(item => item.user.username == arguments[0])
                    .map(item => item.text)
                    .reduce((item, total) => item + '\\n' + total, '');
                return owner_comments;}
            else {
                return null;}
        """,
            user_name,
        )

    if owner_comments == "":
        owner_comments = None
    '''

    # added this line instead 
    owner_comments = None

**Comment by sector13ghost** [comment]
> 

It is now liking 1 photo and then I am getting more errors:
 
 
  File "C:\python\Insta\instabot.py", line 12, in <module>
    session.like_by_tags(['cats','funnypets'], amount = 10)
  File "C:\Users\X\AppData\Local\Programs\Python\Python310\lib\site-packages\instapy\instapy.py", line 2059, in like_by_tags
    success = process_comments(
  File "C:\Users\X\AppData\Local\Programs\Python\Python310\lib\site-packages\instapy\comment_util.py", line 445, in process_comments
    commented_image, message = verify_commented_image(browser, link, owner, logger)
  File "C:\Users\X\AppData\Local\Programs\Python\Python310\lib\site-packages\instapy\comment_util.py", line 366, in verify_commented_image
    data = getMediaData("edge_media_to_parent_comment", browser)
  File "C:\Users\X\AppData\Local\Programs\Python\Python310\lib\site-packages\instapy\util.py", line 523, in getMediaData
    data = additional_data["graphql"]["shortcode_media"]
KeyError: 'graphql'

Any known fixes to this?

**Comment by Chessy11** [comment]
https://github.com/InstaPy/InstaPy/pull/6467

Check this one .
