### ISSUE TITLE
Got an issue 'attributeError: 'NoneType' object has no attribute 'get'

### ISSUE THREAD

**Issue by xProSen** [InstaPy/instapy-quickstart#264]
here's the full code:
PS C:\Users\a\Desktop> py bot.py
InstaPy Version: 0.6.16
 ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.
Workspace in use: "C:/Users/a/InstaPy"
OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
INFO [2022-06-11 19:23:28] [itayabergell]  Session started!
oooooooooooooooooooooooooooooooooooooooooooooooooooooo
INFO [2022-06-11 19:23:36] [i]  - Cookie file for user '...' loaded...
..................................................................
INFO [2022-06-11 19:24:03]   Logged in successfully!
''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
INFO [2022-06-11 19:24:03] [i]  Saving account progress...
INFO [2022-06-11 19:24:56] [  Failed to get followers count of 'b'...''  ~empty list
INFO [2022-06-11 19:25:46] []  Failed to get following count of 'b'...''  ~empty list
WARNING [2022-06-11 19:25:46] [...]  Unable to save account progress, skipping data update
        b"'NoneType' object has no attribute 'get'"
Traceback (most recent call last):
  File "C:\Users\\Desktop\bot.py", line 9, in <module>
    session.login()
  File "C:\Users\\AppData\Local\Programs\Python\Python310\lib\site-packages\instapy\instapy.py", line 475, in login
    self.followed_by = log_follower_num(self.browser, self.username, self.logfolder)
  File "C:\Usersי\AppData\Local\Programs\Python\Python310\lib\site-packages\instapy\print_log_writer.py", line 21, in log_follower_num
    followed_by = getUserData("graphql.user.edge_followed_by.count", browser)
  File "C:\Users\\AppData\Local\Programs\Python\Python310\lib\site-packages\instapy\util.py", line 501, in getUserData
    get_key = shared_data.get("entry_data").get("ProfilePage")
AttributeError: 'NoneType' object has no attribute 'get'
PS C:\Users\a\Desktop>

**Comment by bri-vax** [comment]
Same issue

**Comment by hassen2010** [comment]
Same issue

**Comment by mateusz-myczkowski** [comment]
Same issue.

**Comment by theoakdigital** [comment]
Same issue here. Did you find a solution on that?

**Comment by NomanBaigA** [comment]
Same issue

**Comment by aru12** [comment]
Hi.

I have same issue.

Not get `shared_data`  in `getUserData` method.(The value of the variable `shared_data` is `None`)
But I don't know why.

**Comment by mohamadkazemt** [comment]
Same issue

**Comment by TimskiB** [comment]
Same here.

**Comment by hamishcrichton** [comment]
Same issue

**Comment by TimskiB** [comment]
It seems like the chain of problems starts at this code snippet from util.py:

```
def get_shared_data(browser):
    """
    Get shared data object from page source
    Code by schealex

    :param browser: The selenium webdriver instance
    :return shared_data: Json data from window._sharedData extracted from page source
    """
    shared_data = None
    soup = BeautifulSoup(browser.page_source, "html.parser")
    for text in soup(text=re.compile(r"window._sharedData")):
        if re.search("^window._sharedData", text):
            shared_data = json.loads(re.search("{.*}", text).group())
            break

    return shared_data
```

shared_data is probably None at the end of the function, right? any ideas?

**Comment by Huhnicorn** [comment]
Same issue.

**Comment by nekojin116** [comment]
same issues

**Comment by pedrobart** [comment]
same here

**Comment by shreesha345** [comment]
same issue

**Comment by Brrake** [comment]
I found a workaround in util.py at line 1118: 


` def format_number (number) :

    formatted_num = number.replace(",", "")
    formatted_num = formatted_num.replace("\nfollowers", "")
    formatted_num = formatted_num.replace("\nfollowing", "")

    formatted_num = re.sub(
        r"(k)$", "00" if "." in formatted_num else "000", formatted_num
    )
    formatted_num = re.sub(
        r"(m)$", "00000" if "." in formatted_num else "000000", formatted_num
    )
    formatted_num = formatted_num.replace(".", "")
    return formatted_num
`
