### ISSUE TITLE
]  Failed to get followers count of 'b'myusername''  ~empty list

### ISSUE THREAD

**Issue by sephiroth986** [InstaPy/instapy-quickstart#269]
hi 

i have installed instapy and emoji. next i have launched follow unfollow script, but i receive alway this message: 

..................................................................
INFO [2022-07-26 14:43:49] [sephiroth986]  Logged in successfully!
''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
INFO [2022-07-26 14:43:49] [sephiroth986]  Saving account progress...
INFO [2022-07-26 14:44:41] [sephiroth986]  Failed to get followers count of 'b'sephiroth986''  ~empty list
INFO [2022-07-26 14:45:32] [sephiroth986]  Failed to get following count of 'b'sephiroth986''  ~empty list
WARNING [2022-07-26 14:45:32] [sephiroth986]  Unable to save account progress, skipping data update 
	b"'NoneType' object has no attribute 'get'"

INFO [2022-07-26 14:45:33] [sephiroth986]  Sessional Live Report:
	|> No any statistics to show

[Session lasted 2.43 minutes]
OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
INFO [2022-07-26 14:45:33] [sephiroth986]  Session ended!
ooooooooooooooooooooooooooooooooooooooooooooooooooooooooo

Traceback (most recent call last):
  File "C:\Users\orazi\AppData\Local\Programs\Python\Python310\Lib\site-packages\quickstart.py", line 58, in <module>
    with smart_run(session):
  File "C:\Users\orazi\AppData\Local\Programs\Python\Python310\lib\contextlib.py", line 135, in __enter__
    return next(self.gen)
  File "C:\Users\orazi\AppData\Local\Programs\Python\Python310\Lib\site-packages\instapy\util.py", line 1983, in smart_run
    session.login()
  File "C:\Users\orazi\AppData\Local\Programs\Python\Python310\Lib\site-packages\instapy\instapy.py", line 475, in login
    self.followed_by = log_follower_num(self.browser, self.username, self.logfolder)
  File "C:\Users\orazi\AppData\Local\Programs\Python\Python310\Lib\site-packages\instapy\print_log_writer.py", line 21, in log_follower_num
    followed_by = getUserData("graphql.user.edge_followed_by.count", browser)
  File "C:\Users\orazi\AppData\Local\Programs\Python\Python310\Lib\site-packages\instapy\util.py", line 501, in getUserData
    get_key = shared_data.get("entry_data").get("ProfilePage")
AttributeError: 'NoneType' object has no attribute 'get'

**Comment by pedrobart** [comment]
same

**Comment by tamasgara04** [comment]
Same

**Comment by jayeshjain18** [comment]
same please solve this issue!

**Comment by matifali** [comment]
is it the same when the account has less than 100 followers?

**Comment by GersonRosales** [comment]
Same!

**Comment by matifali** [comment]
use your email in place of username

**Comment by callum80041** [comment]
> use your email in place of username

this didn't resolve the issue for me. Both User ID and Email generate the same error.

**Comment by yukrix** [comment]
stuck here too
