### ISSUE TITLE
Issue when running quickstart for instapy

### ISSUE THREAD

**Issue by walidapnea** [InstaPy/instapy-quickstart#27]
Hi everybody, I keep on getting this error after installing and running quickstart for Mac:

Starting InstaPy with quickstart
====================
Traceback (most recent call last):
  File "../quickstart.py", line 2, in <module>
    from instapy import InstaPy
  File "/Library/Python/2.7/site-packages/instapy-0.3.3-py2.7.egg/instapy/__init__.py", line 3, in <module>
    from .instapy import InstaPy
  File "/Library/Python/2.7/site-packages/instapy-0.3.3-py2.7.egg/instapy/instapy.py", line 22, in <module>
    from .clarifai_util import check_image
  File "/Library/Python/2.7/site-packages/instapy-0.3.3-py2.7.egg/instapy/clarifai_util.py", line 4, in <module>
    from clarifai.rest import Workflow
ImportError: cannot import name Workflow
logout
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

**Comment by timgrossmann** [comment]
https://github.com/timgrossmann/InstaPy/issues/3270
