### ISSUE TITLE
instapy not working

### ISSUE THREAD

**Issue by lucasrhb** [InstaPy/instapy-quickstart#273]
Can someone point me in the right direction what is wrong?
Installed everything, fresh ubuntu 22.04 installation, cloned repo and I've that:

$ python3 simple_interaction_good_for_beginners.py
Traceback (most recent call last):
  File "/root/instapy-quickstart/quickstart_templates/simple_interaction_good_for_beginners.py", line 14, in <module>
    from instapy import InstaPy
  File "/usr/local/lib/python3.10/dist-packages/instapy/__init__.py", line 6, in <module>
    from .instapy import InstaPy
  File "/usr/local/lib/python3.10/dist-packages/instapy/instapy.py", line 34, in <module>
    from .browser import close_browser, set_selenium_local_session
  File "/usr/local/lib/python3.10/dist-packages/instapy/browser.py", line 14, in <module>
    from .util import interruption_handler
  File "/usr/local/lib/python3.10/dist-packages/instapy/util.py", line 27, in <module>
    from emoji.unicode_codes import UNICODE_EMOJI
ImportError: cannot import name 'UNICODE_EMOJI' from 'emoji.unicode_codes' (/usr/local/lib/python3.10/dist-packages/emoji/unicode_codes/__init__.py)

**Comment by MightyM00n** [comment]
i have same problem did you solve it?

**Comment by eastcoastboys** [comment]
I am also having the same issue...

**Comment by dgslv** [comment]
hey mates,

you can find the answer you guys are looking for at https://stackoverflow.com/questions/73108683/getting-error-cannot-import-name-unicode-emoji-from-emoji-unicode-codes.

also faced this and solved it by doing it right it was described there.
