### ISSUE TITLE
Error On windows_start.bat

### ISSUE THREAD

**Issue by Llama894** [InstaPy/instapy-quickstart#277]
starting instapy with quickstart
================================
Traceback (most recent call last):
  File "C:\Users\fillin\AppData\Local\Programs\Python\Python311\instapy-quickstart-master\instapy-quickstart-master\quickstart.py", line 2, in <module>
    from instapy import InstaPy
  File "C:\Users\fillin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\instapy\__init__.py", line 6, in <module>
    from .instapy import InstaPy
  File "C:\Users\fillinAppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\instapy\instapy.py", line 34, in <module>
    from .browser import close_browser, set_selenium_local_session
  File "C:\Users\fillin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\instapy\browser.py", line 14, in <module>
    from .util import interruption_handler
  File "C:\Users\fillin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\instapy\util.py", line 27, in <module>
    from emoji.unicode_codes import UNICODE_EMOJI
ImportError: cannot import name 'UNICODE_EMOJI' from 'emoji.unicode_codes' (C:\Users\fillin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\emoji\unicode_codes\__init__.py)
Press any key to continue . . .

**Comment by Konejo06** [comment]
Yo hice esta wea y nadie me ayuda, no se como verlo
