### ISSUE TITLE
ERRORS ERRORS ERRORS!!!! PLEASE HELP

### ISSUE THREAD

**Issue by Ampdale** [InstaPy/instapy-quickstart#282]
starting instapy with quickstart
================================
Traceback (most recent call last):
  File "../quickstart.py", line 2, in <module>
    from instapy import InstaPy
  File "F:\Python\lib\site-packages\instapy\__init__.py", line 6, in <module>
    from .instapy import InstaPy
  File "F:\Python\lib\site-packages\instapy\instapy.py", line 35, in <module>
    from .clarifai_util import check_image
  File "F:\Python\lib\site-packages\instapy\clarifai_util.py", line 3, in <module>
    from clarifai.rest import ClarifaiApp, Workflow
ModuleNotFoundError: No module named 'clarifai.rest'

**Comment by Raidtron** [comment]
pip uninstall clarifai
pip install clarifai==2.6.2
