### ISSUE TITLE
Cannot install on Mac 10.14.2

### ISSUE THREAD

**Issue by bria-n** [InstaPy/instapy-quickstart#3]
Hi there, I'm running into an issue when installing InstaPy using the Install.command under MacOS Installation. Please see below:

```
Using cached https://files.pythonhosted.org/packages/61/29/1549f61917eadd11650e42b78b4afcfe9cb467157af4510ab8cb59535f14/googleapis-common-protos-1.5.6.tar.gz
Installing collected packages: six, grpcio, idna, urllib3, certifi, chardet, requests, EasyProcess, emoji, functools32, jsonschema, plyer, selenium, instapy-chromedriver, PyVirtualDisplay, future, protobuf, regex, PyYAML, MeaningCloud-python, googleapis-common-protos, clarifai, instapy
  Found existing installation: six 1.4.1
Cannot uninstall 'six'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall.
====================
There was a problem installing InstaPy, please copy the error message and create an issue here: https://github.com/InstaPy/instapy-quickstart/issues


Full thread below:

Last login: Mon Feb  4 12:05:44 on console
Brians-MacMachine:~ Brian$ /Users/Brian/Downloads/instapy-quickstart-master/installation/MacOs/install.command ; exit;
/Users/Brian/Downloads/instapy-quickstart-master/installation/MacOs/install.command: line 3: [: !=: unary operator expected
Python is installed
====================
Pip is installed
====================
Chrome is installed
====================
Installing InstaPy...
Collecting instapy
  Using cached https://files.pythonhosted.org/packages/b7/f2/5bc92a59ed3cc9450e2a9149aa19b7aee1f616cbeb199d39485b34969c2d/instapy-0.1.1-py2.py3-none-any.whl
Collecting grpcio>=1.16.1 (from instapy)
  Using cached https://files.pythonhosted.org/packages/35/c2/546d5c216f3daa8020c147dcb338db19cf3a641714f83e5c6622cf800f06/grpcio-1.18.0-cp27-cp27m-macosx_10_9_x86_64.whl
Collecting idna>=2.7 (from instapy)
  Using cached https://files.pythonhosted.org/packages/14/2c/cd551d81dbe15200be1cf41cd03869a46fe7226e7450af7a6545bfc474c9/idna-2.8-py2.py3-none-any.whl
Collecting requests>=2.20.1 (from instapy)
  Using cached https://files.pythonhosted.org/packages/7d/e3/20f3d364d6c8e5d2353c72a67778eb189176f08e873c9900e10c0287b84b/requests-2.21.0-py2.py3-none-any.whl
Collecting EasyProcess>=0.2.3 (from instapy)
  Using cached https://files.pythonhosted.org/packages/45/3a/4eecc0c7995a13a64739bbedc0d3691fc574245b7e79cff81905aa0c2b38/EasyProcess-0.2.5.tar.gz
Collecting urllib3>=1.24.1 (from instapy)
  Using cached https://files.pythonhosted.org/packages/62/00/ee1d7de624db8ba7090d1226aebefab96a2c71cd5cfa7629d6ad3f61b79e/urllib3-1.24.1-py2.py3-none-any.whl
Collecting emoji>=0.5.1 (from instapy)
  Using cached https://files.pythonhosted.org/packages/41/5a/5b2cbaf1f8936e54a3756c4f0587cbe0615cd50c6b31340214ea61f92782/emoji-0.5.1.tar.gz
Collecting certifi>=2018.10.15 (from instapy)
  Using cached https://files.pythonhosted.org/packages/9f/e0/accfc1b56b57e9750eba272e24c4dddeac86852c2bebd1236674d7887e8a/certifi-2018.11.29-py2.py3-none-any.whl
Collecting jsonschema>=2.6.0 (from instapy)
  Using cached https://files.pythonhosted.org/packages/77/de/47e35a97b2b05c2fadbec67d44cfcdcd09b8086951b331d82de90d2912da/jsonschema-2.6.0-py2.py3-none-any.whl
Collecting chardet>=3.0.4 (from instapy)
  Using cached https://files.pythonhosted.org/packages/bc/a9/01ffebfb562e4274b6487b4bb1ddec7ca55ec7510b22e4c51f14098443b8/chardet-3.0.4-py2.py3-none-any.whl
Collecting plyer>=1.3.1 (from instapy)
  Using cached https://files.pythonhosted.org/packages/22/8c/3bdd25b9e489fa62b06937b51dc2611844e58108f458c8e12ea6de7c5db3/plyer-1.4.0.tar.gz
Collecting selenium>=3.141.0 (from instapy)
  Using cached https://files.pythonhosted.org/packages/80/d6/4294f0b4bce4de0abf13e17190289f9d0613b0a44e5dd6a7f5ca98459853/selenium-3.141.0-py2.py3-none-any.whl
Collecting instapy-chromedriver==2.44 (from instapy)
  Using cached https://files.pythonhosted.org/packages/d6/ef/7706399f705534d0fc56269ec03dd9a87dd86a53b341b3bd3640d36fd8f3/instapy-chromedriver-2.44.tar.gz
Collecting PyVirtualDisplay>=0.2.1 (from instapy)
  Using cached https://files.pythonhosted.org/packages/39/37/f285403a09cc261c56b6574baace1bdcf4b8c7428c8a7239cbba137bc0eb/PyVirtualDisplay-0.2.1.tar.gz
Collecting future>=0.17.1 (from instapy)
  Using cached https://files.pythonhosted.org/packages/90/52/e20466b85000a181e1e144fd8305caf2cf475e2f9674e797b222f8105f5f/future-0.17.1.tar.gz
Collecting protobuf>=3.6.1 (from instapy)
  Using cached https://files.pythonhosted.org/packages/2b/2b/d51219eb18a140836cb656053e5408cd18fd752217ff73ca596204cd3183/protobuf-3.6.1-cp27-cp27m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl
Collecting regex>=2018.11.22 (from instapy)
  Using cached https://files.pythonhosted.org/packages/f5/35/6dc256e648a0386a79fb6a456498bfd0ff1dcfc725c9894994e12fd239c2/regex-2019.02.03.tar.gz
Collecting six>=1.11.0 (from instapy)
  Using cached https://files.pythonhosted.org/packages/73/fb/00a976f728d0d1fecfe898238ce23f502a721c0ac0ecfedb80e0d88c64e9/six-1.12.0-py2.py3-none-any.whl
Requirement already satisfied: configparser>=3.5.0 in ./Library/Python/2.7/lib/python/site-packages (from instapy) (3.5.0)
Collecting PyYAML>=3.13 (from instapy)
  Using cached https://files.pythonhosted.org/packages/9e/a3/1d13970c3f36777c583f136c136f804d70f500168edc1edea6daa7200769/PyYAML-3.13.tar.gz
Collecting MeaningCloud-python>=1.1.1 (from instapy)
  Using cached https://files.pythonhosted.org/packages/28/c6/deb6c9d113f94ec99116ec4017b333660ce54344734d29f0cb98fdf32945/MeaningCloud_python-1.1.1-py2.py3-none-any.whl
Collecting clarifai>=2.4.1 (from instapy)
  Using cached https://files.pythonhosted.org/packages/ca/aa/9153ee6afe041b4c4010170ebb862ee867e4431cb7ac9fae0392686e4f88/clarifai-2.5.2-py2-none-any.whl
Requirement already satisfied: enum34>=1.0.4 in ./Library/Python/2.7/lib/python/site-packages (from grpcio>=1.16.1->instapy) (1.1.6)
Requirement already satisfied: futures>=2.2.0 in ./Library/Python/2.7/lib/python/site-packages (from grpcio>=1.16.1->instapy) (3.2.0)
Collecting functools32; python_version == "2.7" (from jsonschema>=2.6.0->instapy)
  Using cached https://files.pythonhosted.org/packages/c5/60/6ac26ad05857c601308d8fb9e87fa36d0ebf889423f47c3502ef034365db/functools32-3.2.3-2.tar.gz
Requirement already satisfied: setuptools in /System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python (from protobuf>=3.6.1->instapy) (18.5)
Collecting googleapis-common-protos<2,>=1.5.0 (from clarifai>=2.4.1->instapy)
  Using cached https://files.pythonhosted.org/packages/61/29/1549f61917eadd11650e42b78b4afcfe9cb467157af4510ab8cb59535f14/googleapis-common-protos-1.5.6.tar.gz
Installing collected packages: six, grpcio, idna, urllib3, certifi, chardet, requests, EasyProcess, emoji, functools32, jsonschema, plyer, selenium, instapy-chromedriver, PyVirtualDisplay, future, protobuf, regex, PyYAML, MeaningCloud-python, googleapis-common-protos, clarifai, instapy
  Found existing installation: six 1.4.1
Cannot uninstall 'six'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall.
====================
There was a problem installing InstaPy, please copy the error message and create an issue here: https://github.com/InstaPy/instapy-quickstart/issues

You can also manually install InstaPy with this guide: https://github.com/timgrossmann/InstaPy

Sorry for the inconveniences
logout
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

[Process completed]


```
Any suggestions?

**Comment by bria-n** [comment]
Sorry, I'm not sure why all the text was bolded.

**Comment by bria-n** [comment]
Just a quick update for anyone who is experiencing the same problem, or might know of a fix..

I believe that I may have successfully installed it, however I'm not 100% sure it will work yet. I did the following:

- Created a virtual environment with "python3 -m venv env"
- "source ./env/bin/activate"
- Using the virtual environment, the following commands appears to have worked "Pip install -U instapy --upgrade --ignore-installed six"
- Will update...

**Comment by bria-n** [comment]
Tried running the script and I could not get it to run:

Last login: Mon Feb  4 12:50:06 on ttys000
Brians-MacMachine:~ Brian$ /Users/Brian/Downloads/instapy-quickstart-master/run/mac_start.command ; exit;
Starting InstaPy with quickstart
====================
Traceback (most recent call last):
  File "../quickstart.py", line 3, in <module>
    from instapy import InstaPy
ImportError: No module named instapy
logout
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

[Process completed]


Also tried it in that previously mentioned virtual environment, and I got a ton of different errors:

 ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._. 
Workspace in use: "/Users/Brian/InstaPy"
WARNING [2019-02-04 12:52:36] [None]  Heeh! Error occurred while getting a DB profile for 'None':
	b'NOT NULL constraint failed: profiles.name'
Traceback (most recent call last):
  File "../quickstart.py", line 14, in <module>
    headless_browser=False)
  File "/Users/Brian/env/lib/python3.7/site-packages/instapy/instapy.py", line 273, in __init__
    get_database(make=True)  # IMPORTANT: think twice before relocating
  File "/Users/Brian/env/lib/python3.7/site-packages/instapy/database_engine.py", line 54, in get_database
    id = get_profile(name, address, logger) if id is None or make else id
  File "/Users/Brian/env/lib/python3.7/site-packages/instapy/database_engine.py", line 137, in get_profile
    profile = dict(profile)
TypeError: 'NoneType' object is not iterable


I'll have to try installing/running InstaPy later. Have to get back to work. Please comment if you have any tips/suggestions. Thanks.

**Comment by nokia6290** [comment]
Do you have Xcode full software installed in your system?

**Comment by timgrossmann** [comment]
Yeah, sometimes distutils make problems, just use `--ignore-installed` to install new ones without uninstalling the old ones.
Also, make sure your build tools are up to date and working: 
https://github.com/InstaPy/instapy-docs/blob/master/BUILD_TOOLS.md
