### ISSUE TITLE
Issue in final running with unicode emoji

### ISSUE THREAD

**Issue by Czaib** [InstaPy/instapy-quickstart#303]
starting instapy with quickstart
================================
Traceback (most recent call last):
  File "C:\instapy\instapy-quickstart-master\instapy-quickstart-master\quickstart.py", line 14, in <module>
    from instapy import InstaPy
  File "C:\Python310\lib\site-packages\instapy\__init__.py", line 6, in <module>
    from .instapy import InstaPy
  File "C:\Python310\lib\site-packages\instapy\instapy.py", line 34, in <module>
    from .browser import close_browser, set_selenium_local_session
  File "C:\Python310\lib\site-packages\instapy\browser.py", line 14, in <module>
    from .util import interruption_handler
  File "C:\Python310\lib\site-packages\instapy\util.py", line 27, in <module>
    from emoji.unicode_codes import UNICODE_EMOJI
ImportError: cannot import name 'UNICODE_EMOJI' from 'emoji.unicode_codes' (C:\Python310\lib\site-packages\emoji\unicode_codes\__init__.py)
Press any key to continue . . .

**Comment by gqchishti** [comment]
pip uninstall emoji
pip install emoji==1.7

**Comment by Czaib** [comment]
> pip uninstall emoji pip install emoji==1.7

 from instapy import InstaPy
  File "C:\Users\Konain's PC\AppData\Local\Programs\Python\Python312\Lib\site-packages\instapy\__init__.py", line 6, in <module>
    from .instapy import InstaPy
  File "C:\Users\Konain's PC\AppData\Local\Programs\Python\Python312\Lib\site-packages\instapy\instapy.py", line 35, in <module>
    from .clarifai_util import check_image
  File "C:\Users\Konain's PC\AppData\Local\Programs\Python\Python312\Lib\site-packages\instapy\clarifai_util.py", line 3, in <module>
    from clarifai.rest import ClarifaiApp, Workflow
  File "C:\Users\Konain's PC\AppData\Local\Programs\Python\Python312\Lib\site-packages\clarifai\rest\__init__.py", line 3, in <module>
    from clarifai.rest.client import ApiClient
  File "C:\Users\Konain's PC\AppData\Local\Programs\Python\Python312\Lib\site-packages\clarifai\rest\client.py", line 21, in <module>
    from future.moves.urllib.parse import urlparse
  File "C:\Users\Konain's PC\AppData\Local\Programs\Python\Python312\Lib\site-packages\future\moves\__init__.py", line 5, in <module>
    from future.standard_library import import_top_level_modules
  File "C:\Users\Konain's PC\AppData\Local\Programs\Python\Python312\Lib\site-packages\future\standard_library\__init__.py", line 65, in <module>
    import imp
ModuleNotFoundError: No module named 'imp'
PS C:\Users\Konain's PC\Downloads\instapy new\InstaPy-master>

**Comment by gqchishti** [comment]
use python 3.11.7 as in python 3.12 they have depreciated the imp module

**Comment by gqchishti** [comment]
however this repository have a lot of issues as it not properly maintained and instagram has changed alot since.

**Comment by abg5f** [comment]
@gqchishti do you have any others programs updated and maintained ?

**Comment by gqchishti** [comment]
instagrapi seems to be updated but it uses api instead of selenium. I haven't tried it much but with some coding you can customize it the way you want it to be.

**Comment by GLouv** [comment]
anyone knows if this is still running?
