### ISSUE TITLE
mac_start.command Issue/Error

### ISSUE THREAD

**Issue by ionevan** [InstaPy/instapy-quickstart#40]
I have successfully installed instapy but when trying to run **mac_start.command** from instapy quickstart, I get the following:

Ivans-MacBook:~ ivan$ /Users/ivan/Downloads/instapy-quickstart-master/run/mac_start.command ; exit;
Starting InstaPy with quickstart
====================

 ._.  ._.  ._.  ._.  ._.  ._.  ._. 
Workspace in use: "/Users/ivan/InstaPy"
WARNING [2019-05-30 13:02:15] [None]  Heeh! Error occurred while getting a DB profile for 'None':
	NOT NULL constraint failed: profiles.name
Traceback (most recent call last):
  File "../quickstart.py", line 24, in <module>
    headless_browser=False)
  File "/Library/Python/2.7/site-packages/instapy/instapy.py", line 292, in __init__
    get_database(make=True)  # IMPORTANT: think twice before relocating
  File "/Library/Python/2.7/site-packages/instapy/database_engine.py", line 60, in get_database
    id = get_profile(name, address, logger) if id is None or make else id
  File "/Library/Python/2.7/site-packages/instapy/database_engine.py", line 147, in get_profile
    profile = dict(profile)
TypeError: 'NoneType' object is not iterable
logout
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.
Deleting expired sessions...none found.

[Process completed]

Any help would be appreciated!

**Comment by hollossy** [comment]
Could you paste a copy of the Quickstart script you use?

**Comment by ionevan** [comment]
@hollossy sure thing, please see below:

# imports
from instapy import InstaPy
from instapy import smart_run

# login credentials
insta_username = ''
insta_password = ''

comments = ['Nice shot! @{}',
        'I love your profile! @{}',
        'Your feed is an inspiration :thumbsup:',
        'Just incredible :open_mouth:',
        'What camera did you use @{}?',
        'Love your posts @{}',
        'Looks awesome @{}',
        'Getting inspired by you @{}',
        ':raised_hands: Yes!',
        'I can feel your passion @{} :muscle:']

# get an InstaPy session!
# set headless_browser=True to run InstaPy in the background
session = InstaPy(username=insta_username,
                  password=insta_password,
                  headless_browser=False)

with smart_run(session):
  """ Activity flow """		
  # general settings		
  session.set_dont_include(["friend1", "friend2", "friend3"])		
  
  # activity		
  session.like_by_tags(["natgeo"], amount=10)

  # Joining Engagement Pods
  session.set_do_comment(enabled=True, percentage=35)
  session.set_comments(comments)
  session.join_pods()

**Comment by hollossy** [comment]
Well sorry but I'm not sure, maybe this can help:
https://stackoverflow.com/questions/3887381/typeerror-nonetype-object-is-not-iterable-in-python

**Comment by ionevan** [comment]
@hollossy I'll have a look! Thanks for your help regardless :)
