### ISSUE TITLE
selenium.common.exceptions.WebDriverException: Message: unknown error: Chrome failed to start: exited abnormally

### ISSUE THREAD

**Issue by Patatone** [InstaPy/instapy-quickstart#48]
My system: Centos 7, i tried to install all requirements by this script: https://gist.github.com/kaze/eb35d0a815553204cb6d1a9129b20163
but i got this error:

`[root@musicbot instapy-quickstart]# python3.6 quickstart.py
Traceback (most recent call last):
  File "quickstart.py", line 2, in <module>
    from instapy import InstaPy
  File "/usr/lib/python3.6/site-packages/instapy/__init__.py", line 3, in <module>
    from .instapy import InstaPy
  File "/usr/lib/python3.6/site-packages/instapy/instapy.py", line 25, in <module>
    from .clarifai_util import check_image
  File "/usr/lib/python3.6/site-packages/instapy/clarifai_util.py", line 3, in <module>
    from clarifai.rest import ClarifaiApp
  File "/usr/lib/python3.6/site-packages/clarifai/rest/__init__.py", line 3, in <module>
    from clarifai.rest.client import ApiClient
  File "/usr/lib/python3.6/site-packages/clarifai/rest/client.py", line 23, in <module>
    from future.moves.urllib.parse import urlparse
  File "/usr/lib/python3.6/site-packages/future/moves/__init__.py", line 8, in <module>
    import_top_level_modules()
  File "/usr/lib/python3.6/site-packages/future/standard_library/__init__.py", line 810, in import_top_level_modules
    with exclude_local_folder_imports(*TOP_LEVEL_MODULES):
  File "/usr/lib/python3.6/site-packages/future/standard_library/__init__.py", line 781, in __enter__
    module = __import__(m, level=0)
  File "/root/instapy-quickstart/test.py", line 17, in <module>
    driver = webdriver.Chrome('/usr/local/bin/chromedriver',chrome_options=chrome_options)
  File "/usr/lib/python3.6/site-packages/selenium/webdriver/chrome/webdriver.py", line 81, in __init__
    desired_capabilities=desired_capabilities)
  File "/usr/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "/usr/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/usr/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/usr/lib/python3.6/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: Chrome failed to start: exited abnormally
  (Driver info: chromedriver=2.35.528139 (47ead77cb35ad2a9a83248b292151462a66cd881),platform=Linux 3.10.0 x86_64)
`

**Comment by beewigs** [comment]
Use headless_browser=True
