### ISSUE TITLE
Error occurred while following through dialog box: 'follow'

### ISSUE THREAD

**Issue by ianpierreg** [InstaPy/instapy-quickstart#49]
Does someone know what it is about? It occurs while loading the followers using of some profile that I intend to follow. As soons as it finishes loading the list, the program crashes giving me the following error:

```
OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
INFO [2019-07-05 00:17:14] [emagreca_sem.loucuras]  Session ended!
oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo



Traceback (most recent call last):
  File "quickstart.py", line 52, in <module>
    randomize=False, interact=False)
  File "/home/oxeanbits/.local/lib/python3.6/site-packages/instapy/instapy.py", line 3255, in follow_user_followers
    interact)
  File "/home/oxeanbits/.local/lib/python3.6/site-packages/instapy/instapy.py", line 1088, in follow_by_list
    self.logfolder)
  File "/home/oxeanbits/.local/lib/python3.6/site-packages/instapy/unfollow_util.py", line 764, in follow_user
    naply = get_action_delay("follow")
  File "/home/oxeanbits/.local/lib/python3.6/site-packages/instapy/util.py", line 1771, in get_action_delay
    custom_delay = config[action]
KeyError: 'follow'

```

I'm using the template `basic_follow-unfollow_activity.py`.

It does follow 5 people before crashing though.

**Comment by lzomedia** [comment]
me to I get the same error, mine doesn't follow

**Comment by reidmeyer** [comment]
same. and also not verifying follows. temporarily blocked even after waiting a few days
