### ISSUE TITLE
Instapy incompatible with the 76 version of Chrome?

### ISSUE THREAD

**Issue by Muwoly** [InstaPy/instapy-quickstart#63]
Hi everyone,
Since about a week, Instapy does not seems to be compatible with the last version of Google Chrome.

` ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.
INFO [2019-08-06 11:07:47] [*******]  Using built in instapy-chromedriver executable (version 2.46)

DevTools listening on ws://127.0.0.1:50865/devtools/browser/15c5e83e-bf10-4f25-b6ae-0dbb23e9332a
ERROR [2019-08-06 11:07:51] [*******]  Message: session not created: Chrome version must be between 71 and 75
  (Driver info: chromedriver=2.46.628402 (536cd7adbad73a3783fdc2cab92ab2ba7ec361e1),platform=Windows NT 10.0.17134 x86_64)
Traceback (most recent call last):
  File "C:\Users\loris\AppData\Local\Programs\Python\Python37-32\lib\site-packages\instapy\browser.py", line 163, in set_selenium_local_session
    chrome_options=chrome_options)
  File "C:\Users\loris\AppData\Local\Programs\Python\Python37-32\lib\site-packages\selenium\webdriver\chrome\webdriver.py", line 81, in __init__
    desired_capabilities=desired_capabilities)
  File "C:\Users\loris\AppData\Local\Programs\Python\Python37-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "C:\Users\loris\AppData\Local\Programs\Python\Python37-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "C:\Users\loris\AppData\Local\Programs\Python\Python37-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\loris\AppData\Local\Programs\Python\Python37-32\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: session not created: Chrome version must be between 71 and 75
  (Driver info: chromedriver=2.46.628402 (536cd7adbad73a3783fdc2cab92ab2ba7ec361e1),platform=Windows NT 10.0.17134 x86_64)`

I thought about installing the 75 version of Chrome but is there any other way I can make it run?
Do you think there may be a different problem?

**Comment by kadudutra** [comment]
I have the same problem

**Comment by crisjun27** [comment]
Same Problem with new version of 76 Chrome..
Can anyone know how to solve this?

**Comment by Muwoly** [comment]
Guys I find the solution. You can either 
- Download the 75th version of chrome and block the updates by desactivating the google updates on your task manager.
- Run Instapy on Firefox by adding the code below to your script. If needed, [this vid](https://www.youtube.com/watch?v=iTyK5KGNx-Y) will help you add geckodriver. (This is how I did it and it works just fine)

> session = InstaPy(username=insta_username, password=insta_password, use_firefox=True)
 
Running Instapy on Firefox is the solution I opt for

**Comment by dinzrus** [comment]
I also experienced like this, I think the cause of the problem is that new chrome renamed its chrome driver to chromedriver.exe, when instapy couldn't find the driver, it will use it's own package chrome driver which is not compatible with the new chrome, what I do is I download the latest chrome driver 
here https://chromedriver.chromium.org/ version 76 and replaced the instapy package chrome driver which you can find in this directory env/lib/site_packages/instapy_chromedriver/ , the new filename of the chrome driver is only chromedriver.exe so you need to change it to what instapy know, which is chromedriver_win32.exe. That's it. I know it will be solved soon by updating your instapy installation.

**Comment by mofe23** [comment]
@dinzrus answer worked for me, watch out that instapy stores 3 chromedriver executables for all os with a prefix. dont forget to rename the newly downloaded file

1. find your site-packages folder
`python -m site`

2. backup old chromedriver
`mv site-packages/instapy_chromedriver/chromedriver_mac64 site-packages/instapy_chromedriver/chromedriver_mac64.bak`

3. Download new chromedriver for your os [here](https://chromedriver.storage.googleapis.com/index.html?path=76.0.3809.68/) & extract archive

4. Move new chromedriver to location
`mv ~/Downloads/chromedriver site-packages/instapy_chromedriver/chromedriver_mac64`

**Comment by LizarPh** [comment]
> I also experienced like this, I think the cause of the problem is that new chrome renamed its chrome driver to chromedriver.exe, when instapy couldn't find the driver, it will use it's own package chrome driver which is not compatible with the new chrome, what I do is I download the latest chrome driver
> here https://chromedriver.chromium.org/ version 76 and replaced the instapy package chrome driver which you can find in this directory env/lib/site_packages/instapy_chromedriver/ , the new filename of the chrome driver is only chromedriver.exe so you need to change it to what instapy know, which is chromedriver_win32.exe.
> 
> That's it. I know it will be solved soon by updating your instapy installation.

It worked perfectly for me. Thanks, man

**Comment by saharavishag** [comment]
> I also experienced like this, I think the cause of the problem is that new chrome renamed its chrome driver to chromedriver.exe, when instapy couldn't find the driver, it will use it's own package chrome driver which is not compatible with the new chrome, what I do is I download the latest chrome driver
> here https://chromedriver.chromium.org/ version 76 and replaced the instapy package chrome driver which you can find in this directory env/lib/site_packages/instapy_chromedriver/ , the new filename of the chrome driver is only chromedriver.exe so you need to change it to what instapy know, which is chromedriver_win32.exe.
> 
> That's it. I know it will be solved soon by updating your instapy installation.

works amazing! thanks!

**Comment by avipars** [comment]
> I also experienced like this, I think the cause of the problem is that new chrome renamed its chrome driver to chromedriver.exe, when instapy couldn't find the driver, it will use it's own package chrome driver which is not compatible with the new chrome, what I do is I download the latest chrome driver
> here https://chromedriver.chromium.org/ version 76 and replaced the instapy package chrome driver which you can find in this directory env/lib/site_packages/instapy_chromedriver/ , the new filename of the chrome driver is only chromedriver.exe so you need to change it to what instapy know, which is chromedriver_win32.exe.
> 
> That's it. I know it will be solved soon by updating your instapy installation.

@dinzrus Can you help me do this for windows?
