### ISSUE TITLE
Do I have to downgrade my google chrome?

### ISSUE THREAD

**Issue by GreatMalboro** [InstaPy/instapy-quickstart#68]
I think there is something im not understanding about the versions. So do my chrome driver and google chrome browser have to be the same? I saw someone saying to just update them both but nothing happen.

Theres no rush to get to me but I would like an idea on what im supposed to be doing,

Windows 10. 64Bit. 

Edit: I have downgraded chrome. No avail ok. My instapy was just working a few days ago. Should I be attempting a fresh install? Im going to try that as a last resort and come back with another edit. Im a bit new to this.

Edit: I cannot figure out what I may have done to my files the last error I get is

"No moduel named 'instapy.event." 

Cannot find solution.

Final note before surrender:
I used instapy quickstart to no avail. heres my errors and code. Currently it opens a window and closes it after entering ID.

```
CODE
`# imports
from instapy import InstaPy
from instapy import smart_run

# login credentials
insta_username = 'herp'
insta_password = 'derp'

comments = ['Nice shot! @{}',
        'I love your profile! @{}',
        'Your feed is an inspiration :thumbsup:',
        'Just incredible :open_mouth:',
        'What camera did you use @{}?',
        'Love your posts @{}',
        'Looks awesome @{}',
        'Getting inspired by you @{}',
        ':raised_hands: Yes!',
        'I can feel your passion @{} :muscle:']

# get an InstaPy session!
# set headless_browser=True to run InstaPy in the background
session = InstaPy(username=insta_username,
                  password=insta_password,
                  headless_browser=False)

with smart_run(session):
  """ Activity flow """		
  # general settings		
  session.set_dont_include(["friend1", "friend2", "friend3"])		
  
  # activity		
  session.like_by_tags(["natgeo"], amount=10)

  # Joining Engagement Pods
  session.set_do_comment(enabled=True, percentage=35)
  session.set_comments(comments)
  session.join_pods(topic='sports', engagement_mode='heavy')
`

ERROR

` RESTART: C:\Users\Higher Thoughts\Desktop\instapy-quickstart-master\quickstart.py 

 ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._. 
Workspace in use: "C:/Users/Higher Thoughts/InstaPy"

 ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._. 
INFO [2019-08-13 04:02:18] [derp]  Using built in instapy-chromedriver executable (version 2.46)

OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
INFO [2019-08-13 04:02:22] [herp]  Session started!
oooooooooooooooooooooooooooooooooooooooooooooooooooooo

Cookie file not found, creating cookie...
**********************************************************************
If raising an issue, please also upload the file located at:
C:\Users\HIGHER~1\AppData\Local\Temp\20190813-040305.html
**********************************************************************

INFO [2019-08-13 04:03:08] [derp]  Sessional Live Report:
	|> No any statistics to show


[Session lasted 49.69 seconds]

OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
INFO [2019-08-13 04:03:08] [herp]  Session ended!
ooooooooooooooooooooooooooooooooooooooooooooooooooooooooo



Traceback (most recent call last):
  File "C:\Users\Higher Thoughts\Desktop\instapy-quickstart-master\quickstart.py", line 26, in <module>
    with smart_run(session):
  File "C:\Users\Higher Thoughts\AppData\Local\Programs\Python\Python37-32\lib\contextlib.py", line 112, in __enter__
    return next(self.gen)
  File "C:\Users\Higher Thoughts\AppData\Local\Programs\Python\Python37-32\lib\site-packages\instapy\util.py", line 1676, in smart_run
    session.login()
  File "C:\Users\Higher Thoughts\AppData\Local\Programs\Python\Python37-32\lib\site-packages\instapy\instapy.py", line 378, in login
    self.bypass_with_mobile):
  File "C:\Users\Higher Thoughts\AppData\Local\Programs\Python\Python37-32\lib\site-packages\instapy\login_util.py", line 262, in login_user
    "//button//div[text()='Log in']")
  File "C:\Users\Higher Thoughts\AppData\Local\Programs\Python\Python37-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "C:\Users\Higher Thoughts\AppData\Local\Programs\Python\Python37-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 978, in find_element
    'value': value})['value']
  File "C:\Users\Higher Thoughts\AppData\Local\Programs\Python\Python37-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Higher Thoughts\AppData\Local\Programs\Python\Python37-32\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//button//div[text()='Log in']"}
  (Session info: chrome=71.0.3578.80)
  (Driver info: chromedriver=2.46.628402 (536cd7adbad73a3783fdc2cab92ab2ba7ec361e1),platform=Windows NT 10.0.17134 x86_64)
`
```

**Comment by o365geek** [comment]
You must have chromedriver:https://sites.google.com/a/chromium.org/chromedriver/

Make you have chromedriver installed . By the way have you follow the steps in @timgrossmann instapy-quickstart?
