### ISSUE TITLE
I installed python, pip, selenium and request but still no luck

### ISSUE THREAD

**Issue by stkrules2** [InstaPy/instapy-quickstart#76]
Expected result should've been the bot starting the browser and doing its stuff but 

These are the errors that i am getting right now

Traceback (most recent call last):
  File "C:\Users\no shit\AppData\Local\Programs\Python\Python37-32\Lib\site-packages\quickstart.py", line 24, in <module>
    headless_browser=False)
  File "C:\Users\no shit\AppData\Local\Programs\Python\Python37-32\Lib\site-packages\instapy\instapy.py", line 318, in __init__
    self.logger,
  File "C:\Users\no shit\AppData\Local\Programs\Python\Python37-32\Lib\site-packages\instapy\browser.py", line 114, in set_selenium_local_session
    options=firefox_options,
  File "C:\Users\no shit\AppData\Local\Programs\Python\Python37-32\Lib\site-packages\selenium\webdriver\firefox\webdriver.py", line 174, in __init__
    keep_alive=True)
  File "C:\Users\no shit\AppData\Local\Programs\Python\Python37-32\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "C:\Users\no shit\AppData\Local\Programs\Python\Python37-32\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "C:\Users\no shit\AppData\Local\Programs\Python\Python37-32\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\no shit\AppData\Local\Programs\Python\Python37-32\Lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: Unable to find a matching set of capabilities

**Comment by ravzzy** [comment]
I was able to solve this by downgrading both instapy to 0..5.8 and chrome version to 75. 
See if this works for you.
