### ISSUE TITLE
Keep getting this error even tried starting a fresh instapy using the default quick start.

### ISSUE THREAD

**Issue by thankmelater23** [InstaPy/instapy-quickstart#79]
'python belize-lottery.py
Traceback (most recent call last):
  File "belize-lottery.py", line 3, in <module>
    from instapy import InstaPy
  File "/Users/AndreVillanueva_Com/Dropbox/bots/InstaPy/instapy/__init__.py", line 3, in <module>
    from .instapy import InstaPy
  File "/Users/AndreVillanueva_Com/Dropbox/bots/InstaPy/instapy/instapy.py", line 104
    username: str = None,
            ^
SyntaxError: invalid syntax'

**Comment by Tonners15** [comment]
Same Issue
