### ISSUE TITLE
selenium.common.exceptions.SessionNotCreatedException

### ISSUE THREAD

**Issue by valikaovalikao** [InstaPy/instapy-quickstart#82]
While trying to run the code 
I got this message at the end 
selenium.common.exceptions.SessionNotCreatedException: 

My chrome and python are updated

**Comment by praful-dhabekar** [comment]
> While trying to run the code
> I got this message at the end
> selenium.common.exceptions.SessionNotCreatedException:
> 
> My chrome and python are updated

**I've got the same issue below is my log from Windows 10 64bit**

`InstaPy Version: 0.6.2
 ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.
Workspace in use: "C:/Users/pddha/InstaPy"
Traceback (most recent call last):
  File "quickstart.py", line 24, in <module>
    headless_browser=True)
  File "C:\Users\pddha\AppData\Local\Programs\Python\Python37\lib\site-packages\instapy\instapy.py", line 321, in __init__
    self.logger,
  File "C:\Users\pddha\AppData\Local\Programs\Python\Python37\lib\site-packages\instapy\browser.py", line 114, in set_selenium_local_session
    options=firefox_options,
  File "C:\Users\pddha\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\firefox\webdriver.py", line 174, in __init__
    keep_alive=True)
  File "C:\Users\pddha\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "C:\Users\pddha\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "C:\Users\pddha\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\pddha\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: Unable to find a matching set of capabilities`


**below is my log from Ubuntu 64bit**

`Traceback (most recent call last):
  File "quickstart.py", line 24, in <module>
    headless_browser=True)
  File "/usr/local/lib/python3.6/dist-packages/instapy/instapy.py", line 321, in __init__
    self.logger,
  File "/usr/local/lib/python3.6/dist-packages/instapy/browser.py", line 114, in set_selenium_local_session
    options=firefox_options,
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/firefox/webdriver.py", line 174, in __init__
    keep_alive=True)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: Unable to find a matching set of capabilities`

_Help me, please._

**Comment by lucasrhb** [comment]
Debian 9 (up to date) and Ubuntu 16.04 (up to date) are the same:

selenium.common.exceptions.SessionNotCreatedException: Message: Unable to find a matching set of capabilities

Both freshly installed today.

**Comment by avipars** [comment]
From my understanding, you'll need to roll-back chrome to a version before 75. Google changed the name of the chrome driver in newer versions of it's browser.

**Comment by adamlh** [comment]
Any official mirrors for previous Chrome releases?

**Comment by avipars** [comment]
I believe there aren't any official mirrors, but a simple google search can return some unofficial mirrors.

**Comment by lucasrhb** [comment]
Would that not be easier to fix/modify script to use current version?

**Comment by avipars** [comment]
I am not a maintainer, but I believe it would be easier to change the script.
