### ISSUE TITLE
Won't start

### ISSUE THREAD

**Issue by lucasrhb** [InstaPy/instapy-quickstart#92]
New DO droplet. All installed as in manual and:

~/instapy-quickstart/quickstart_templates# python3 good_commenting_strategy_and_new_qs_system.py 
InstaPy Version: 0.6.3
 ._.  ._.  ._.  ._.  ._.  ._.  ._. 
Workspace in use: "/root/InstaPy"
Traceback (most recent call last):
  File "good_commenting_strategy_and_new_qs_system.py", line 29, in <module>
    proxy_port='', headless_browser=True)
  File "/usr/local/lib/python3.5/dist-packages/instapy/instapy.py", line 321, in __init__
    self.logger,
  File "/usr/local/lib/python3.5/dist-packages/instapy/browser.py", line 114, in set_selenium_local_session
    options=firefox_options,
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/firefox/webdriver.py", line 174, in __init__
    keep_alive=True)
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: Unable to find a matching set of capabilities

**Comment by avipars** [comment]
Seems to be an issue with the newest version of chrome

**Comment by lucasrhb** [comment]
Any other solution thatn downgrading chrome?

**Comment by debashisxyz** [comment]
This might be due to headless-browser=False inside quickstart.py. Make it True
