### ISSUE TITLE
Unable to start browser

### ISSUE THREAD

**Issue by naksharaa** [InstaPy/instapy-quickstart#93]
Traceback (most recent call last):
  File "E:\Instagram\Files\11 new\InstaPy-master\quickstart.py", line 4, in <module>
    from instapy import InstaPy
  File "E:\Instagram\Files\11 new\InstaPy-master\instapy\__init__.py", line 6, in <module>
    from .instapy import InstaPy
  File "E:\Instagram\Files\11 new\InstaPy-master\instapy\instapy.py", line 82, in <module>
    from .browser import set_selenium_local_session
  File "E:\Instagram\Files\11 new\InstaPy-master\instapy\browser.py", line 7, in <module>
    from webdriverdownloader import GeckoDriverDownloader
ModuleNotFoundError: No module named 'webdriverdownloader'
>>>

**Comment by avipars** [comment]
Did you run pip install instapy and the installation batch file in the installation folder for windows?
