### ISSUE TITLE
Selenium webdriver unable to find a matching set of capabilities error

### ISSUE THREAD

**Issue by Paris778** [InstaPy/instapy-quickstart#96]
**### //These are the errors I get even when using the default quickstart script. Please help**

InstaPy Version: 0.6.4
 ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._. 
Workspace in use: "C:/Users/User/InstaPy"    
Traceback (most recent call last):
  File "c:/Users/User/Desktop/quickstart.py", line 14, in <module>
    headless_browser=False)
  File "C:\Users\User\AppData\Local\Programs\Python\Python37\lib\site-packages\instapy\instapy.py", line 321, in __init__
    self.logger,
  File "C:\Users\User\AppData\Local\Programs\Python\Python37\lib\site-packages\instapy\browser.py", line 114, in set_selenium_local_session
    options=firefox_options,
  File "C:\Users\User\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\firefox\webdriver.py", line 174, in __init__
    keep_alive=True)
  File "C:\Users\User\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "C:\Users\User\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "C:\Users\User\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\User\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
**selenium.common.exceptions.SessionNotCreatedException: **Message: Unable to find a matching set of capabilities****

**Comment by Rhydderch** [comment]
I get the same error.
In another issue, somebody says we should use chrome version 75 to make it work, but I don't know how to downgrade on digitalocean server or on windows.

**Comment by Luismi74** [comment]
> I get the same error.
> In another issue, somebody says we should use chrome version 75 to make it work, but I don't know how to downgrade on digitalocean server or on windows.

This might work:
Uninstall Chrome and install this version: https://www.filepuma.com/download/google_chrome_64bit_75.0.3770.100-22588/
