### ISSUE TITLE
Freshly installed on MacOS - doesn't work

### ISSUE THREAD

**Issue by lucasrhb** [InstaPy/instapy-quickstart#99]
InstaPy Version: 0.6.4
 ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._. 
Workspace in use: "/Users/lucasrhb/InstaPy"
1801kb [00:01, 1280.68kb/s]                                                                                                                                                                                 
Traceback (most recent call last):
  File "like_by_tag_interact_unfollow.py", line 41, in <module>
    headless_browser=True)
  File "/usr/local/lib/python3.7/site-packages/instapy/instapy.py", line 321, in __init__
    self.logger,
  File "/usr/local/lib/python3.7/site-packages/instapy/browser.py", line 114, in set_selenium_local_session
    options=firefox_options,
  File "/usr/local/lib/python3.7/site-packages/selenium/webdriver/firefox/webdriver.py", line 174, in __init__
    keep_alive=True)
  File "/usr/local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "/usr/local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/usr/local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: Unable to find a matching set of capabilities

**Comment by khea7en** [comment]
I replaced Python 3 with 2.7.16 and was able to get it to work, but whenever I run mac_start.command I get a whole different issue

Hope that at least helps you move from here

**Comment by karahan0** [comment]
Do u slove the problem?

**Comment by karahan0** [comment]
> InstaPy Version: 0.6.4
> ._. ._. ._. ._. ._. ._. ._. ._.
> Workspace in use: "/Users/lucasrhb/InstaPy"
> 1801kb [00:01, 1280.68kb/s]
> Traceback (most recent call last):
> File "like_by_tag_interact_unfollow.py", line 41, in 
> headless_browser=True)
> File "/usr/local/lib/python3.7/site-packages/instapy/instapy.py", line 321, in **init**
> self.logger,
> File "/usr/local/lib/python3.7/site-packages/instapy/browser.py", line 114, in set_selenium_local_session
> options=firefox_options,
> File "/usr/local/lib/python3.7/site-packages/selenium/webdriver/firefox/webdriver.py", line 174, in **init**
> keep_alive=True)
> File "/usr/local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 157, in **init**
> self.start_session(capabilities, browser_profile)
> File "/usr/local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 252, in start_session
> response = self.execute(Command.NEW_SESSION, parameters)
> File "/usr/local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
> self.error_handler.check_response(response)
> File "/usr/local/lib/python3.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
> raise exception_class(message, screen, stacktrace)
> selenium.common.exceptions.SessionNotCreatedException: Message: Unable to find a matching set of capabilities

I have the same error ! @khea7en u need to use python3 InstaPy is not working with python2
